### ISSUE TITLE
Wheel builds broken by CentOS repository going offline

### ISSUE THREAD

**Issue by matthew-brett** [pypa/manylinux#100]
CentOS5 just went end-of-life - see #96 .

In consequence (I guess) the repositories that the docker image expect have disappeared, and any manylinux build trying to access these repositories has broken - e.g.:

* https://travis-ci.org/python-pillow/pillow-wheels/jobs/218267819
* https://travis-ci.org/MacPython/matplotlib-wheels/jobs/218370911

It looks like we need to update the docker image to use still-existing repos such as 

http://vault.centos.org/5.11/

See: https://mail.python.org/pipermail/distutils-sig/2017-April/030362.html

**Comment by matthew-brett** [comment]
Hours I think.   I'll look at it later today.

**Comment by squeaky-pl** [comment]
5.11 just started failing several minutes ago for me.

http://centos.mirrors.nublue.co.uk/5.11/os/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404: Not Found

**Comment by larsbutler** [comment]
I just ran into this issue as well.

What about moving to a newer version of CentOS, rather than trying to patch things up with 5?

**Comment by squeaky-pl** [comment]
@larsbutler that needs a PEP, new tag and a process.

**Comment by matthew-brett** [comment]
https://github.com/pypa/manylinux/pull/102 may fix this.  Needs merging, and then we need to wait for the docker images to update.  Maybe another 12 hours if all goes well?

**Comment by njsmith** [comment]
Merged, so new docker images should be available in ~30 minutes?

@larsbutler: We'd love to move to a newer release, but it will take a bit of work and we need help :-) If you're interested in helping out, there's a bit of a checklist here: https://mail.python.org/pipermail/distutils-sig/2017-April/030361.html

**Comment by larsbutler** [comment]
@njsmith Awesome, thanks for resolving this so quickly!

After digging into the build scripts further, I realized how non-trivial such an update would be. :) I'm not sure how helpful I can be, but I'll take a look and at least try to educate myself.

**Comment by matthew-brett** [comment]
Fresh numpy wheels builds working now : https://travis-ci.org/MacPython/numpy-wheels/builds/218374431

**Comment by wiredfool** [comment]
Pillow wheels are working now as well: https://travis-ci.org/python-pillow/pillow-wheels/jobs/218570143
