### ISSUE TITLE
pip-compile based requirements.txt

### ISSUE THREAD

**Issue by henryiii** [pypa/manylinux#1019]
I've started thinking about a pip-compile based requirements generation; I've started by writing this `noxfile.py`:

```python
import nox

@nox.session(python=["2.7", "3.5", "3.6", "3.7", "3.8", "3.9"])
def compile(session):
    session.install("pip-tools")
    session.chdir("docker/build_scripts")
    session.run("pip-compile", "--generate-hashes", "requirements.in", "--output-file", f"requirements{session.python}.txt")
```

And this `requirements.in`:

```
pip
setuptools
wheel
build
```

However, pip and setuptools are missing from the output. Maybe a known issue with pip-compile? (since they are already installed) Don't know, so just dumping the current status here.

**Comment by wbolster** [comment]
i think you would need to add the `--allow-unsafe` flag, which will also become the default in the future: https://github.com/jazzband/pip-tools#deprecations

**Comment by henryiii** [comment]
Thanks, this seems to be working:

```python
import nox

@nox.session(python=["2.7", "3.5", "3.6", "3.7", "3.8", "3.9"])
def compile(session):
    session.install("pip-tools")
    session.run("pip-compile", "--generate-hashes", "requirements.in", "--allow-unsafe", "--output-file", f"docker/build_scripts/requirements{session.python}.txt")
```

**Comment by wbolster** [comment]
cool :+1: maybe this issue can be closed then, @henryiii?

**Comment by henryiii** [comment]
I'll like to leave it as a placeholder until I get a pr ready. The only hard part is loading the different compiled requirements files.

(Though I can still access this if you really want it closed sooner)
