### ISSUE TITLE
Unnecessary to install `kernel-devel-$(uname -r)` in `manylinux1` builder container ?

### ISSUE THREAD

**Issue by xuyang2** [pypa/manylinux#1056]
Is seems unnecessary to `yum install kernel-devel-$(uname -r)` in the centos:5 container.
Anyway, `uname -r` in the container returns the kernel release of the host.

Code:
https://github.com/pypa/manylinux/blob/dbd36f78489bc4049947e6164e28d8a755ab5932/docker/build_scripts/build.sh#L72-L78

Build log:
https://github.com/pypa/manylinux/runs/2192738056?check_suite_focus=true#step:3:380

	 + yum -y install automake bison bzip2 cmake28 devtoolset-2-binutils devtoolset-2-gcc devtoolset-2-gcc-c++ devtoolset-2-gcc-gfortran diffutils expat-devel gettext kernel-devel-5.4.0-1041-azure file make patch unzip which yasm zlib-devel bzip2-devel ncurses-devel sqlite-devel readline-devel tk-devel gdbm-devel db4-devel libpcap-devel xz-devel gpg libffi-devel
	Reducing CentOS-5 - libselinux to included packages only
	Finished
	Setting up Install Process
	Package diffutils-2.8.1-16.el5.x86_64 already installed and latest version
	No package kernel-devel-5.4.0-1041-azure available.

**Comment by xuyang2** [comment]
And `git grep kernel-devel` shows nothing except for the `manylinux1` branch.
Seems already fixed in main branch.
Relative PRs and commits:

- https://github.com/pypa/manylinux/pull/348
- https://github.com/pypa/manylinux/pull/348/files#diff-06397b64e9d4c44493c709ff2d96d126e1ff66b2ee25999c267882770ac7b185R83
- https://github.com/pypa/manylinux/commit/03edd4119707002d8bba475d53737adc31edc0c1#diff-06397b64e9d4c44493c709ff2d96d126e1ff66b2ee25999c267882770ac7b185R83

- https://github.com/pypa/manylinux/pull/979
- https://github.com/pypa/manylinux/pull/979/files#diff-6356f7ab4b0cce5102991e023f7b3d076661846a9b5d0493d984de2c9fcb4e9cR13
- https://github.com/pypa/manylinux/commit/8c24b01cac5b35dd4e8e75a2aac74e33838cfdd2#diff-6356f7ab4b0cce5102991e023f7b3d076661846a9b5d0493d984de2c9fcb4e9cR13

**Comment by mayeut** [comment]
Thanks for the report. This is now fixed.
