### ISSUE TITLE
[Question] Do any Docker images have clang installed? 

### ISSUE THREAD

**Issue by lanctot** [pypa/manylinux#1066]
I have tried manylinux2010, 2014, and 2_24, and seem to be unable to find clang++ in the path (via cibuildwheel). 

Just curious if it is not installed or installed in a separate location outside the path? Thanks!

**Comment by mayeut** [comment]
Hi @lanctot, clang is not installed. I don't know if it's available through `yum install` or `apt-get install` and, even if available, if it would create a manylinux compliant wheel.

**Comment by lanctot** [comment]
Oh sorry I should have closed the issue. I was anle to compile everything with g++ in the end, thanks for the response!
