### ISSUE TITLE
is it possible to have intel compiler in manylinux docker image?

### ISSUE THREAD

**Issue by QINQINKONG** [pypa/manylinux#1096]
Hi. I'm trying to use manylinux docker container to distribute a python package with a C extension compiled by cython. Since my code works fine if compiled by intel compiler, but not good (the scipy.optimize.brentq function cannot converge sometimes) if compiled by gcc compiler. Also icc is faster than gcc in my case. So I would like to distribute a precompiled binary using intel compiler. However, it seems that we don't have intel compiler in manylinux docker container. Is it possible to install it? Or does it still comply to the manylinux policy if I use intel compiler?

Thanks!

**Comment by matthew-brett** [comment]
I think your only option will be to make such an image yourself, by building on top of an existing Manylinux image, or installing the compiler on the fly in your build.

The resulting wheel will have some Intel license implications, as you'll inevitably end up shipping their run-time routines somehow - so you might want to work out some way of warning your installing users what they are consenting to.  I haven't looked into this in a while, but you might want to check whether the user of your wheel has to agree not to disassemble the binary code or redistribute the code, and whether you, the distributor, are liable for Intel's legal costs if someone sues them as a result of using your software.

**Comment by QINQINKONG** [comment]
Thanks for the so quick reply! I can try to make this image myself. Also, does it mean that using intel compiler doesn't violate the manylinux policy, and I would be still able to upload the generated wheel onto PyPi?

**Comment by QINQINKONG** [comment]
> I think your only option will be to make such an image yourself, by building on top of an existing Manylinux image, or installing the compiler on the fly in your build.
> 
> The resulting wheel will have some Intel license implications, as you'll inevitably end up shipping their run-time routines somehow - so you might want to work out some way of warning your installing users what they are consenting to. I haven't looked into this in a while, but you might want to check whether the user of your wheel has to agree not to disassemble the binary code or redistribute the code, and whether you, the distributor, are liable for Intel's legal costs if someone sues them as a result of using your software.

Thanks for the so quick reply! I can try to make this image myself. Also, does it mean that using intel compiler doesn't violate the manylinux policy, and I would be still able to upload the generated wheel onto PyPi?

**Comment by mayeut** [comment]
To extend a bit on what @matthew-brett wrote (all of which I agree with):
- Intel is publishing some of its runtime libraries On PyPI: https://pypi.org/user/IntelAutomationEngineering/ (search for "-rt" packages)
Wether or not they are redistributing these for convenience or for legal reason given the license (i.e. you shall depend on them and can't redistribute them) is something you should also look into.
- auditwheel doesn't know how to handle those dependencies: https://github.com/pypa/auditwheel/issues/250

> Also, does it mean that using intel compiler doesn't violate the manylinux policy, and I would be still able to upload the generated wheel onto PyPi?

If it passes the auditwheel check, you're good to go but you'll have to try. The dependency stuff with auditwheel might be an issue if you're not allowed to redistribute intel libraries or modify them (because auditwheel WILL modify them). No way to tell this without testing it I guess.

**Comment by QINQINKONG** [comment]
> To extend a bit on what @matthew-brett wrote (all of which I agree with):
> 
> * Intel is publishing some of its runtime libraries On PyPI: https://pypi.org/user/IntelAutomationEngineering/ (search for "-rt" packages)
>   Wether or not they are redistributing these for convenience or for legal reason given the license (i.e. you shall depend on them and can't redistribute them) is something you should also look into.
> * auditwheel doesn't know how to handle those dependencies: [pypa/auditwheel#250](https://github.com/pypa/auditwheel/issues/250)
> 
> > Also, does it mean that using intel compiler doesn't violate the manylinux policy, and I would be still able to upload the generated wheel onto PyPi?
> 
> If it passes the auditwheel check, you're good to go but you'll have to try. The dependency stuff with auditwheel might be an issue if you're not allowed to redistribute intel libraries or modify them (because auditwheel WILL modify them). No way to tell this without testing it I guess.

Thanks for the answer. I just had a look at the intel end user licenses. It's more complicated than I thought! I will definitely pay attention to the license issue if I finally decided to use intel compiler.
