### ISSUE TITLE
Add PyPy?

### ISSUE THREAD

**Issue by henryiii** [pypa/manylinux#1099]
Could the PyPy interpreters (probably starting with the latest one, PyPy3.7 7.3.4 or likely 7.3.5) be added to the manylinux image? This might make it easier to provide different versions (pypy/manylinux is stuck on manylinux 2010 pypy/manylinux#7) and would avoid image issues mentioned in pypy/manylinux#15. 

_see @mattip in https://github.com/pypa/manylinux/issues/1055#issuecomment-842586294_

**Comment by mayeut** [comment]
xref https://github.com/pypy/manylinux/issues/7

**Comment by mattip** [comment]
For x86_64, i386, and arm64 the [official releases](https://www.pypy.org/download_advanced.html) would work great as they are built inside a manylinux2010 docker. For ppc64, ppc64le, and s390x the situation is a little more complex, are Fedora 20, Fedora 21, and Rehat 7.2 respectively close enough to manylinux2014 to be useful?

**Comment by henryiii** [comment]
I'd base it on pypy/manylinux, but yes, maybe those images would have to (at least at first) not include PyPy.

**Comment by mayeut** [comment]
> For ppc64, ppc64le, and s390x the situation is a little more complex, are Fedora 20, Fedora 21, and Rehat 7.2 respectively close enough to manylinux2014 to be useful?

Only s390x would work on manylinux2014 (I expect CentOS 7 to have full ABI compatibility with RHEL 7.2) but not on manylinux_2_24.
Are there any plans to use the same build process as x86_64/i686/aarch64 for s390x/ppc64le (ppc64le has no PyPy3.7 at all) ?

What would be the expectations regarding the versions of PyPy, there are 5 versions for now in the PyPy images.
Given that PyPy 3.6 seems to be abandoned and that manylinux images dropped support for python 2.7, I'd assume that only including PyPy3.7 7.3.4 would be okay for this transition (or wait for 7.3.5, start with 7.3.5rc2) ?

**Comment by henryiii** [comment]
My recommendation would be to just focus on the latest version (PyPy3.7 7.3.4 or PyPy3.7 7.3.5 very soon). If "old" versions of PyPy are needed, then there's the "pypy/manylinux" image. But just sticking with the latest "supported" pypy3's (Usually 1-2 Python versions) seems reasonable? "pypy/manylinux" could provide more comprehensive, classic PyPy support if needed. Or users could use old manylinux images in the future if they need old PyPy versions, just like they have to do now with Python 2.7/3.5.

**Comment by mattip** [comment]
agreed: there is no need to provide older versions of PyPy. We encourage users to upgrade to the latest versions since support for c-extension modules gets better with each release.
