### ISSUE TITLE
use travis's new "build stages" feature?

### ISSUE THREAD

**Issue by njsmith** [pypa/manylinux#112]
Travis-CI just announced a new feature for [build stages](https://docs.travis-ci.com/user/build-stages):

"For example, you can configure a deployment stage to run only after several test jobs have all completed successfully."

Maybe we can/should use it?

**Comment by mayeut** [comment]
There's no data persistence between jobs which limits its use.
Caching only works in specific conditions (used for manylinux2010 for example) https://docs.travis-ci.com/user/caching#caches-and-build-matrices

It's not appropriate for a wider usage than what's done in manylinux2010. This would require a staging repo in `quay.io` and I don't think it's worth the effort.
