### ISSUE TITLE
Can I still get manylinux images that contain a python 2 interpreter?

### ISSUE THREAD

**Issue by con-f-use** [pypa/manylinux#1124]
I realize Python 2 has been EOL for a very long time. But are there still manylinux images around that can build wheels for it?

**Comment by henryiii** [comment]
manylinux1 still has it (though it will be no longer supported after Jan 1, 2022). There are also final releases with Python 2 available - see the list on the 1.x branch of cibuildwheel - those are the final images that had Python 2.7 (since the 1.x series of cibuildwheel builds Python 2 & 3.5) - https://github.com/pypa/cibuildwheel/blob/1.x/cibuildwheel/resources/pinned_docker_images.cfg

**Comment by con-f-use** [comment]
Sorry for being dumb but I pulled the image for you link and can't find python2.7 in there:

```
[root@3c170e16d0fd io]# ls -al /opt/python/
total 0
drwxr-xr-x 2 root root 94 May  1 12:49 .
drwxr-xr-x 5 root root 47 May  1 12:49 ..
lrwxrwxrwx 1 root root 29 May  1 12:49 cp35-cp35m -> /opt/_internal/cpython-3.5.10
lrwxrwxrwx 1 root root 29 May  1 12:49 cp36-cp36m -> /opt/_internal/cpython-3.6.13
lrwxrwxrwx 1 root root 29 May  1 12:49 cp37-cp37m -> /opt/_internal/cpython-3.7.10
lrwxrwxrwx 1 root root 28 May  1 12:49 cp38-cp38 -> /opt/_internal/cpython-3.8.9
lrwxrwxrwx 1 root root 28 May  1 12:49 cp39-cp39 -> /opt/_internal/cpython-3.9.4
```

**Comment by henryiii** [comment]
Which image? `manylinux2014` and `manylinux_2_24` has never supported Python 2. It's only manylinux1 (any version) and manylinux2010 (linked tags) that support it.

**Comment by henryiii** [comment]
Pip 9 is still pretty common for Python 2.7 distributions, so I'd likely recommend manylinux1 for Python 2 anyway. You need pip 19 or newer to be able to download a manylinux 2010 wheel. Anything before pip 21 supports Python 2, but users on Python 2 are pretty likely to have old versions of things anyway, possibly including pip.

**Comment by con-f-use** [comment]
Never mind, as suspected I was just being dumb with docker tags. Thanks for the tips, I have no functioning wheels for a little bit of software forensics.
