### ISSUE TITLE
Understanding compiled manilinux tags

### ISSUE THREAD

**Issue by kennylajara** [pypa/manylinux#1137]
Hi, I have program, lets name it Example and say the version is 1.0.

I compiled my program Example for python 3.7, 3.8 and 3.9. This generated 3 files: `Example-1.0-cp37-cp37m-linux_x86_64.whl`, `Example-1.0-cp38-cp38-linux_x86_64.whl`, `Example-1.0-cp39-cp39-linux_x86_64.whl`.

I repaired each of these files with `manylinux2014` and `manilinux_2_24` so, I ended up with 6 files in the `wheelhouse` folder. When I repaired for `manilinux_2_24`, `manylinux2014` is also included in the name of the generated file. Example:

The python 3.9 repaired with `manilinux_2_24` generated a file named `Example-1.0-cp39-cp39-manilinux_2_17_x86_64.manilinux2014_x86_64.manilinux_2_24_x86_64.whl` while `manilinux_2014` generated a file named `Example-1.0-cp39-cp39-manilinux_2_17_x86_64.manilinux2014_x86_64.whl`

So, my two questions are:

Does that means that I just need to include the one generated by `manilinux_2_24` in the dist folder to support both versions?

Also, why there is an `m` in the name of the python 3.7 (`cp37-cp37m`) version and but not in the others  (`cp38-cp38` and  `cp39-cp39`)?

**Comment by mayeut** [comment]
does https://github.com/pypa/auditwheel/issues/314 answer your first question ?

> Also, why there is an m in the name of the python 3.7 (cp37-cp37m) version and but not in the others (cp38-cp38 and cp39-cp39)?

Extract from README:
> Note that less common or virtually unheard of flag combinations (such as --with-pydebug (d) and --without-pymalloc (absence of m)) are not provided.
>
> Note that starting with [CPython 3.8](https://docs.python.org/dev/whatsnew/3.8.html#build-and-c-api-changes), default sys.abiflags became an empty string: the m flag for pymalloc became useless (builds with and without pymalloc are ABI compatible) and so has been removed. (e.g. /opt/python/cp38-cp38)

**Comment by kennylajara** [comment]
> does [pypa/auditwheel#314](https://github.com/pypa/auditwheel/issues/314) answer your first question ?

Yes, it does. Both of my questions has been answered. Thank you.
