### ISSUE TITLE
Install devtoolset-10 for manylinux2014

### ISSUE THREAD

**Issue by TonyXiang8787** [pypa/manylinux#1141]
I have noticed that gcc 10 is now available via devtoolset-10 in CentOS 7.

https://centos.pkgs.org/7/centos-sclo-rh-x86_64/devtoolset-10-toolchain-10.1-0.el7.x86_64.rpm.html

Would it be possible to upgrade the gcc/g++ version to 10 for `manylinux2014` image? We can get the most of the C++20 features.

I have briefly read the `Dockerfile` and it seems to only replace the line 

```
TOOLCHAIN_DEPS="devtoolset-9-binutils devtoolset-9-gcc devtoolset-9-gcc-c++ devtoolset-9-gcc-gfortran"
```
into

```
TOOLCHAIN_DEPS="devtoolset-10-binutils devtoolset-10-gcc devtoolset-10-gcc-c++ devtoolset-10-gcc-gfortran"
```

Is that so simple or maybe I have misunderstood the way which the image installs the tool chain?

**Comment by mayeut** [comment]
It's not that simple. The devtoolset-10 is not yet available for every platform, i686 & s390x are lacking this.
For i686, this requires manylinux maintainers to rebuild it using [Copr](https://copr.fedorainfracloud.org) as is done for devtoolset-8 & devtoolset-9
For s390x, this will need to be reported to [Sine Nomine](https://www.sinenomine.net) who manages the ClefOS 7 distribution (or report over at https://github.com/nealef/clefos).

**Comment by matthew-brett** [comment]
Is it sensible to get going without i686 and s390x for now?   My guess is that i686 is becoming a rare requirement - we're thinking of dropping it for Scipy, for example.   I'm afraid I don't know any data for s390x wheel uptake.

**Comment by mayeut** [comment]
> Is it sensible to get going without i686 and s390x for now?

There's been complaints of inconsistent toolchains between architectures in the past so I'm not willing to take that road again.

i686 is still used by 25% of packages so it's not that rare (at least on packager side). s390x is not used that much.
c.f. https://mayeut.github.io/manylinux-timeline/

I'll see if I can get a devtoolset-10 rebuilt for i686 on copr but this will probably take a couple weeks.
For s390x, problems are often quickly resolved when reported (missing devtoolset-10-runtime which prohibits gcc, g++, fortran installation which are built and present in the repo).

In the meantime, if someone doesn't need s390x and i686, it can be installed and activated with:
```
yum install -y devtoolset-10-binutils devtoolset-10-gcc devtoolset-10-gcc-c++ devtoolset-10-gcc-gfortran
source /opt/rh/devtoolset-10/enable
```

**Comment by TonyXiang8787** [comment]
> In the meantime, if someone doesn't need s390x and i686, it can be installed and activated with:

@mayeut This is exactly what our project is doing. The built binary wheel file passes the check of `auditwheel`.
