### ISSUE TITLE
Keep the `test` module

### ISSUE THREAD

**Issue by icemac** [pypa/manylinux#1142]
Besides some other removals #302 removed the `test` module to reduce the image size.

The [zodbpickle](https://github.com/zopefoundation/zodbpickle) project uses the `test` module in its own tests.
In https://github.com/zopefoundation/zodbpickle/pull/63 the `manylinux2014_aarch64` image is used to run the tests before building the wheels.

Is there a possibility to get the `test` module back into the image – either by not removing it or by adding it back afterwards?

**Comment by mayeut** [comment]
Thanks for the report.
The `test` module was removed way before #302 in 265756ed4c4026189d7b417400050562376c4c1f.
I'll check what this would add it terms of size with the newer images.

**Comment by icemac** [comment]
@mayeut Thank you for clarifying the point of removal.
Do you have any news regarding the image sizes?

**Comment by mayeut** [comment]
This would add 40MB uncompressed (on manylinux2014 x86_64) so that does seem reasonable.
I will create a PR to suppress the removal of test modules.

**Comment by icemac** [comment]
Thank you very much for resolving this issue. It helped a lot for zodbpickle as its tests are now green.
