### ISSUE TITLE
PEP513 may be listing wrong limits for version symbols

### ISSUE THREAD

**Issue by molinav** [pypa/manylinux#1148]
The text from [PEP513](../tree/cfe8a6c0/pep-513.rst) says the following:

> Many of the permitted system libraries listed above use symbol versioning schemes for backward compatibility. The latest symbol versions provided with the CentOS 5.11 versions of these libraries are:
> 
> GLIBC_2.5
> CXXABI_3.4.8
> GLIBCXX_3.4.9
> GCC_4.2.0
> 
> Therefore, as a consequence of requirement (b), any wheel that depends on versioned symbols from the above shared libraries may depend only on symbols with the following versions:
> 
> GLIBC <= 2.5
> CXXABI <= 3.4.8
> GLIBCXX <= 3.4.9
> GCC <= 4.2.0

However, if I search these symbol versions in a CentOS 5.11 image I get the following:
```sh
vic@onyx:~$ docker run --rm -it centos:5 sh -c "strings /lib64/libc.so.6 | grep GLIBC"
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_PRIVATE
vic@onyx:~$ docker run --rm -it centos:5 sh -c "strings /usr/lib64/libstdc++.so.6 | grep CXXABI"
CXXABI_1.3
CXXABI_1.3.1
vic@onyx:~$ docker run --rm -it centos:5 sh -c "strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX"
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_FORCE_NEW
```
So it seems to me that PEP513 defines symbol version limits higher than the ones in CentOS 5.11 (and therefore the manylinux1 image). I would be expecting to find in PEP513:
```
GLIBC_2.5
CXXABI_1.3.1
GLIBCXX_3.4.8
GCC_4.2.0
```
for the list of CentOS 5.11 highest symbol versions, and:
```
GLIBC <= 2.5
CXXABI <= 1.3.1
GLIBCXX <= 3.4.8
GCC <= 4.2.0
```
for the upper bound criteria.

Am I missing something?

**Comment by mayeut** [comment]
Hello @molinav,

[PEP 513](https://www.python.org/dev/peps/pep-0513/) has been superseded by [PEP 600](https://www.python.org/dev/peps/pep-0600/).

But yes, you're right about those symbols.
The effective allowed symbol versions allowed for manylinux1/manylinux_2_5 can be found in the [auditwheel manylinux policy file](https://github.com/pypa/auditwheel/blob/b0762a910ef159242d47f601f4605053f23b8e92/auditwheel/policy/manylinux-policy.json#L8-L33).

What's effectively in use is what you mention:
```
GLIBC <= 2.5
CXXABI <= 1.3.1
GLIBCXX <= 3.4.8
GCC <= 4.2.0
```

As PEP 513 is superseded, it won't be updated.
The version you link to is the last working draft of PEP 513 which is still stored in this repo.

**Comment by molinav** [comment]
@mayeut Thanks for the reply! Good to see that it was only a problem in the PEP text but not in the values used by `auditwheel`.
