### ISSUE TITLE
`--enable-shared` is required by Pyinstaller

### ISSUE THREAD

**Issue by ikus060** [pypa/manylinux#1149]
According to PyInstaller https://github.com/pyinstaller/pyinstaller/issues/6066#issuecomment-888333161 manylinux images could not be used to create redistributable package compatible with many linux distribution because the python provided within the images are not compiled with `--enable-shared`

Mostly a question or a feature request, what would be the properly way to have a "manylinux" image with  `--enable-shared` ?

**Comment by mayeut** [comment]
This was done intentionnaly for building wheels which is the use-case of manylinux images.
c.f. https://github.com/pypa/manylinux/issues/255#issuecomment-450761634 & #30 for more details.

If I'm not mistaken, the use-case for pyinstaller only requires 1 python installation to create the "app" package.
This can be done in a "manylinux" friendly way by installing python3-devel on a CentOS base image.
CentOS 7 (base image for manylinux2014) provides 2 versions of python3:
- 3.6.8 through `yum install python3-devel`
- 3.8.6 through `yum install rh-python38-python-devel` (you need to enable `scl-rh` repo for this one: `yum -y install centos-release-scl-rh`)

IMHO, this is the best option for pyinstaller. It also allows not to waste bandwidth/ci time using images that are larger than necessary.

**Comment by ikus060** [comment]
Thanks alot for the information.

Will use manylinux2014 base image and install the required devel package to make it work.
