### ISSUE TITLE
Cannot build C++14 in docker images

### ISSUE THREAD

**Issue by YannickJadoul** [pypa/manylinux#118]
Hello. I'm in the situation where I have a C++14 extension (using the brilliant (pybind11)[https://github.com/pybind/pybind11] library), but the GCC version installed on the docker images are 4.8 and do not support the C++14 standard.

Is there a way I can get around this, and would still be able to produce `manylinux1` wheels?

**Comment by njsmith** [comment]
Unfortunately there aren't any compilers that both support c++14 and can generate manylinux1-compatible (= centos 5 compatible) builds.

However, there is a plan to define `manylinux2` and `manylinux3` standards based on centos6 and centos7, respectively. That's the most likely path to getting c++14 support. Currently there's no one actively working on this, because we're a volunteer run project and none of the existing contributors have the time right now, but it would be a pretty straightforward thing for someone to help with if you want. There's a [rough checklist of what needs to happen in this email](https://mail.python.org/pipermail/distutils-sig/2017-April/030361.html).

**Comment by YannickJadoul** [comment]
Thank you for this quick reply.
Hmm, given that I've been learning quite a lot about all this, over the last few days, I would indeed find it interesting to help (after digging into the internals of the first manylinux). 

Meanwhile, while lacking such a newer standard, what would be the best way forward, on the short term? 'Downgrading' my C++14 code to 11, or building on another system (e.g., Travis CI's Ubuntu 12.04 (precise))?

**Comment by njsmith** [comment]
If you can downgrade your code to c++11, then that'll be the most reliable option, yeah. If you build on another system, then your wheels won't be `manylinux1` compatible, and only `manylinux1` wheels are allowed on pypi currently. Technically I suppose you could lie and label your wheels as being manylinux1-compatible when they aren't, but (a) that would be naughty, and (b) since pip uses the platform tag to determine which systems are compatible with which wheels, lying to it sets up a situation where some of your users may get broken installs. (Of course if you're not distributing these wheels publicly on pypi, then this matters much less.)

I think the manylinux2/3 to-do list is actually pretty approachable if you want to go that way; most of it should be possible to copy directly from the manylinux1 equivalents.

In any case, good luck!

**Comment by rmcgibbo** [comment]
If you're _really_ careful, it might be possible to use a newer version of `g++` with tricks like http://archive.is/wkKoy#selection-129.0-144.0 to generate manylinux1-compatible code, but it requires a pretty high degree of compiler kung fu.

**Comment by mpharrigan** [comment]
Can't you (1) install a new gcc in the docker container and then (2) just vendor libstdc++

**Comment by YannickJadoul** [comment]
@rmcgibbo Thanks, not sure how easy that is (though I'll pay around a little bit, next week), but it's a very nice read on the actual problem!

@mpharrigan The problem is that I can't find a GCC >= 5 for CentOS 5, so are you suggesting to build from source?

**Comment by njsmith** [comment]
Building a recent toolchain and then vendoring libstdc++ would indeed work AFAIK, though I don't know how easy it is.

**Comment by mpharrigan** [comment]
> are you suggesting to build from source?

Yeah

**Comment by YannickJadoul** [comment]
Right, I'll give these different options a shot, over the course of the next week, and see what works best in my case.

**Comment by squeaky-pl** [comment]
I've built multilib GCC 6.3 for Centos 5 for Porable PyPy project: https://github.com/squeaky-pl/centos-devtools/releases

If you manage to convince manylinux docker image to use this compiler instead it might work.

**Comment by rmcgibbo** [comment]
@squeaky-pl: that's impressive. i'm eager to hear if it works for the manylinux case. if so, that would be fantastic.

**Comment by YannickJadoul** [comment]
Wow, this is brilliant! Unpacking and compiling seems to be working like a charm, on my local docker image.

However, I'm still running into a problem with `auditwheel`
```
[root@e46be390efb1 dist]# auditwheel show praat_parselmouth-0.1.0-cp27-cp27m-linux_x86_64.whl 

praat_parselmouth-0.1.0-cp27-cp27m-linux_x86_64.whl is consistent with
the following platform tag: "linux_x86_64".

The wheel references external versioned symbols in these system-
provided shared libraries: libgcc_s.so.1 with versions {'GCC_3.3.1',
'GCC_3.0'}, libstdc++.so.6 with versions {'CXXABI_1.3.5',
'CXXABI_1.3.9', 'CXXABI_1.3', 'GLIBCXX_3.4', 'GLIBCXX_3.4.18',
'GLIBCXX_3.4.20', 'CXXABI_1.3.3', 'GLIBCXX_3.4.21'}, libm.so.6 with
versions {'GLIBC_2.2.5'}, libpthread.so.0 with versions
{'GLIBC_2.2.5', 'GLIBC_2.3.2'}, libc.so.6 with versions
{'GLIBC_2.2.5'}

This constrains the platform tag to "linux_x86_64". In order to
achieve a more compatible tag, you would to recompile a new wheel from
source on a system with earlier versions of these libraries, such as
CentOS 5.
```

So, @squeaky-pl, is your GCC 6.3 also using a more recent version of CXXABI than the standard one on the `manylinux1` CentOS 5?

**Comment by squeaky-pl** [comment]
I am not quite sure because I don't work with C++ at all. The compiler was compiled itself on Centos 5 but of course C++ standard library evolved quite a lot since GCC 4.8.

The PEP itself says:

```
GLIBC <= 2.5 <-- fine
CXXABI <= 3.4.8 <-- fine
GLIBCXX <= 3.4.9 <-- this looks violated
GCC <= 4.2.0 <-- fine
```
So probably this is libstdc++.so.6 that needs to be shipped somehow because it's tightly coupled with compiler version I guess.

**Comment by squeaky-pl** [comment]
@YannickJadoul what about feeding `-static-libstdc++` to the compiler/linker?

**Comment by YannickJadoul** [comment]
Hmmm, I don't know, but I can give that a shot tomorrow. But I'm guessing there's a reason this isn't that standard approach, or not? Any experience with what the size increase of the wheel would be?

**Comment by njsmith** [comment]
I think the issue here is that auditwheel assumes that you want to use the system libstdc++, so when it sees that you're using a newer version it just says "nope, not manylinux!" instead of invoking its vendoring logic. Maybe there should be a way to tell it that no, you really do want to vendor libstdc++ (or similar).

`-static-libstdc++` will make your wheel bigger, but maybe not as much as copying the entire libstdc++.so into your wheel, which is the other option. (Assuming we're sticking with manylinux1 here.) I guess if you have just one extension module using c++ then `-static-libstdc++` should produce a smaller wheel than vendoring, and if you have multiple extension modules using c++ then it's hard to predict.

**Comment by YannickJadoul** [comment]
That dóes work!

```
[root@485583349e21 Parselmouth]# auditwheel show dist/praat_parselmouth-0.1.0-cp27-cp27m-linux_x86_64.whl 

praat_parselmouth-0.1.0-cp27-cp27m-linux_x86_64.whl is consistent with
the following platform tag: "manylinux1_x86_64".

The wheel references external versioned symbols in these system-
provided shared libraries: libgcc_s.so.1 with versions {'GCC_3.0',
'GCC_3.3', 'GCC_3.3.1', 'GCC_4.2.0'}, libpthread.so.0 with versions
{'GLIBC_2.3.2', 'GLIBC_2.2.5'}, libc.so.6 with versions {'GLIBC_2.3',
'GLIBC_2.2.5'}, libm.so.6 with versions {'GLIBC_2.2.5'}

The following external shared libraries are required by the wheel:
{
    "libc.so.6": "/lib64/libc-2.5.so",
    "libgcc_s.so.1": "/lib64/libgcc_s-4.1.2-20080825.so.1",
    "libm.so.6": "/lib64/libm-2.5.so",
    "libpthread.so.0": "/lib64/libpthread-2.5.so"
}
```

Gives me an increase in size from about 2.1 MB (`2122551`) to 2.5 MB (`2510676`), which seems rather reasonable for a 2017 library.
On the other hand, it still feels somehow 'wrong' in principle, and like a 'temporary hack', or not?

**Comment by njsmith** [comment]
Sweet.

It's not really any more of a hack then anything else involved in shipping portable binaries – it's just that this time you got a peek behind the covers at the kind of thing that the docker image and auditwheel are trying to hide from you :-).

In the longer run switching to manylinux2/3 is probably a better solution (if only so you don't have to keep maintaining your own toolchain forever!), but I don't think you need to feel bad about it or anything.

Btw parselmouth looks super cool.

**Comment by squeaky-pl** [comment]
I would say it would be cool (even in the future manylinux2) to let people use whatever C++ standard version they want especially when C++ goes so fast these days. It would be nice to show people that they can use newer compiler and get more manylinux packages, I don't mind maintaining those because I've been doing that already for 3 years.

**Comment by njsmith** [comment]
@squeaky-pl: it's much less of an issue though for manylinux2/3, because for centos6/7 redhat is maintaining more up to date devtools compilers.

**Comment by njsmith** [comment]
...though actually it looks like the latest devtoolset compiler is GCC 5.3, so... maybe I'm wrong.

**Comment by YannickJadoul** [comment]
@njsmith Thanks for the insight! And I dó like the fact that I've now got binary manylinux wheels :-)

I'd actually still be interested in helping with the manylinux2/3, on the longer term, though I don't think I have all the necessary practical knowledge and experience to do all this.

Also, the main 'magic' of Parselmouth is still in the [pybind11](https://github.com/pybind/pybind11) library, as far as I'm concerned; that thing is really awesome ;-)

**Comment by YannickJadoul** [comment]
@squeaky-pl Just out of curiosity: did you actually have to come up with some tricks in order to get that CentOS 5 distribution of GCC 6, or was is 'just a matter of compiling' ?

**Comment by squeaky-pl** [comment]
@YannickJadoul There are not tricks as far as I know. There is "standard GCC bootstraping pain" that might look tricky to somebody who never built GCC from source but it's no different then compiling GCC on a recent distribution in the end. https://github.com/squeaky-pl/centos-devtools you can look into build and build_deps if you are curious.

**Comment by rmcgibbo** [comment]
I think it would be great if we could add some of the information in this thread as instructions for getting modern C++ working in the manylinux1 container to the wiki or readme or something. I think many people would benefit from them.

**Comment by rmcgibbo** [comment]
Is there any possibility of getting runtime problems if a user imports two packages that both use compiled c++ code that statically links different versions of libstdc++?

**Comment by njsmith** [comment]
@rmcgibbo: If you have two extension modules that use C++ internally but that only communicate via python interfaces (i.e., they're not directly linking to each other or smuggling function pointers through pycapsules or something), then you should be OK with either static linking or vendoring libstdc++. (Watch out for cython's `cimport` functionality, which under the covers involves smuggling function pointers through pycapsules; otherwise I think you'll know if you're doing this.)

Also, that's assuming that you're using the standard Python interpreter. If you have Python embedded inside a C++ program then I *think* statically linking libstdc++ will be ok, but vendoring libstdc++ using auditwheel would not. So like, if you think someone might want to use your extension module from inside blender, for example, then stick to statically linking (or just relying on the system libstdc++); don't try to vendor libstdc++.

**Comment by njsmith** [comment]
Actually that blender case is a pretty subtle gotcha – maybe that's an argument for not supporting libstdc++ vendoring in auditwheel, and recommending that people who need a newer libstdc++ do static linking.

**Comment by squeaky-pl** [comment]
Side note. I pushed GCC 7.1 release: https://github.com/squeaky-pl/centos-devtools/releases/tag/7.1

**Comment by YannickJadoul** [comment]
@squeaky-pl I've finally gotten to using your binaries, and they're great! Thanks! Things work out fine on 64-bit.

However, it seems as if that's ónly 64-bit, since my 32-bit builds are failing? Am I doing something wrong, or can't I use these binaries to build on the i686 manylinux docker image?

**Comment by Noctem** [comment]
@YannickJadoul I compiled GCC 7.1 for 32 and 64 bit CentOS 5 [here](https://github.com/Noctem/pogeo-toolchain/releases). You're welcome to use my binaries or [script for building it yourself](https://github.com/Noctem/pogeo-toolchain/blob/master/linux-build.sh).

You can see how I use that in my project [here](https://github.com/Noctem/pogeo/blob/develop/travis/manylinux-build.sh).

**Comment by squeaky-pl** [comment]
@Noctem it's cool that somebody did it. I didn't care about 32bit myself (although the compiler I built is a  multilib so it can emit 32 bit binaries with  `-m32` but that is not always the thing you want).

I am curious if you built also binutils, using old binutils with new gcc can cause miscompilations especially if you use advanced optimizations like link time optimizations.

**Comment by YannickJadoul** [comment]
@Noctem Cool, thanks for letting us know! I managed to compile a 32 bit version myself by now, but it's nicer and a lot easier if someone else is already hosting it as GitHub releases, ofc! ;-)
Quick question, though: any reason your packages are 2 to 3 times the size of @squeaky-pl's builds? (The 32-bit one I built was also 'just' 73 MB instead of the 200 MB of your tar.bz2's.) Normally I wouldn't care that much, but since Travis CI would be downloading these each time, that might make quite a difference on the longer term.

@squeaky-pl I was thinking, but then I reckoned that if there was an easy way of building `manylinux1-i686` wheels on the 64-bit image, this project would only be providing a single docker image, and not both the `x86_64` ánd `i686` ones?

**Comment by squeaky-pl** [comment]
@YannickJadoul I strip the resulting binaries, otherwise they are huge as well.

It's definitely because cross compilation is harder than having separate images due to many tools making extra assumptions.

_Personal opinion_:

Nobody should be caring about 32bit x86 in 2017.

**Comment by YannickJadoul** [comment]
True, but if I'm building for different OSes and Python versions anyway, that 32-bit won't make the big difference anymore. And you never know what systems are still out there ;-)

**Comment by Noctem** [comment]
@squeaky-pl @YannickJadoul Thanks for the tip. I've stripped the binaries and now include binutils as well. [Now the sizes are 60MB for i686 and 65MB for x86-64](https://github.com/Noctem/pogeo-toolchain/releases/tag/v1.3).

**Comment by YannickJadoul** [comment]
@Noctem Cool, thanks! I'll be sure to check it out somewhere over the next few days!

**Comment by YannickJadoul** [comment]
@Noctem Amazing, it's working, thanks! :-)
There's just two things I need to fix in order to get it working: setting the variables `LD_LIBRARY_PATH` (because it couldn't find `libisl.so.15`) and `CC` (because otherwise CMake looks for `cc` in the path and considers that as the system-wide compiler).
So just as some feedback/suggestion, if you'd be interested: I know the latter is fixed by @squeaky-pl by just adding a symlink `cc` to `gcc` when packaging. And the former would maybe be solved by setting the `rpath`? But I don't know enough about those details. (But things perfectly build without all that, and I need to set `CXXFLAGS="-static-libstdc++"` anyway, so these are just minor details ;-) )

**Comment by Noctem** [comment]
@YannickJadoul I symlinked `cc` to `gcc` in my 7.2 build.

I also just set the `LD_LIBRARY_PATH` in my builds. You're welcome to make a pull request to the build script if you want to make that unnecessary, though I probably won't rebuild the binaries until there's a new version of at least one of the components.

**Comment by YannickJadoul** [comment]
@Noctem Thanks for letting me know!
About that `LD_LIBRARY_PATH`: I don't really mind setting the variable. I also don't know enough about that and `rpath` to know immediately what to do, so it's not that urgent for me.

**Comment by TkTech** [comment]
For anyone landing on this issue, I had the same issue but with C++17 features required to build the pysimdjson wheels. I've uploaded a derived manylinux image with gcc8.3 pre-built and is available here -> https://hub.docker.com/r/tktechdocker/manylinux.

If you want to build your own, here's a usable dockerfile:

```
FROM quay.io/pypa/manylinux1_x86_64

LABEL description="A docker image for building portable Python linux binary wheels using modern GCC"
LABEL maintainer="tk@tkte.ch"

ARG GCC_VERSION=8.3.0
ARG GCC_PATH=/usr/local/gcc-$GCC_VERSION

RUN yum -y update && yum -y install \
    curl \
    bison \
    flex \
    && yum clean all

RUN     cd /tmp \
    && curl -L -o gcc.tar.gz "https://ftp.gnu.org/gnu/gcc/gcc-${GCC_VERSION}/gcc-${GCC_VERSION}.tar.gz" \
    && tar xf gcc.tar.gz \
    && cd /tmp/gcc-$GCC_VERSION \
    && contrib/download_prerequisites \
    && mkdir build \
    && cd build \
    && ../configure -v \
        --build=x86_64-linux-gnu \
        --host=x86_64-linux-gnu \
        --target=x86_64-linux-gnu \
        --prefix=/usr/local/gcc-$GCC_VERSION \
        --enable-checking=release \
        --enable-languages=c,c++,fortran \
        --disable-multilib \
        --program-suffix=-$GCC_VERSION \
    && make -j4 \
    && make install-strip \
    && cd /tmp \
    && rm -rf /tmp/gcc-$GCC_VERSION /tmp/gcc.tar.gz
```

If you want to change the version of GCC built into the image just set `$GCC_VERSION` when building.

**Comment by riddell-stan** [comment]
@TkTech 's image worked well for me. If you're building a wheel using it you'll likely need to export at least the following:
```
export CFLAGS="-static-libstdc++"
export CC=/usr/local/gcc-8.3.0/bin/gcc-8.3.0
export CXX=/usr/local/gcc-8.3.0/bin/g++-8.3.0
```

**Comment by YannickJadoul** [comment]
@TkTech This is also only 64 bit, right?
Is it that rare/unnecessary that I'm still offering 32-bit wheels?

**Comment by TkTech** [comment]
@YannickJadoul it is, but you can just change:
```FROM quay.io/pypa/manylinux1_x86_64```
to
```FROM quay.io/pypa/manylinux1_x86```
... to use the 32bit base.

I'm using this image to produce binaries for a tool that uses processor features only available on x86_64 so 32bit wasn't of interest to me.

**Comment by YannickJadoul** [comment]
@TkTech Thanks! Good point; it does seem you're right, indeed. I've just been looking at [numpy](https://pypi.org/project/numpy/#files) and [pandas](https://pypi.org/project/pandas/#files) for guidance on these kinds of things, and they still seem to be offering both manylinux1 and Windows 32-bit binary wheels.

**Comment by matthew-brett** [comment]
32-bit Linux is getting pretty fringe these days, I bet you can get away without.  That's not so for 32-bit Windows, there's still a reasonable percentage of Windows Python installs that are 32-bit.  I estimated it at 35% or a year or so ago: https://github.com/statsmodels/statsmodels/issues/4657#issuecomment-390726164

**Comment by matthew-brett** [comment]
Updating the query now, for the last 30 days of Numpy downloads from PyPI, 32-bit Windows wheels were at 45% for Python 3.7,  50% for Python 2.7, and 27% (oddly) for Python 3.6.  So, yes, still a big appetite for 32-bit on Windows.

**Comment by patrikhuber** [comment]
@matthew-brett I think the main reason for that is that python.org offers people the 32-bit version by default - if you go there on a Windows machine and click "Downloads"/"Download" (on a Windows machine), you'll currently get `python-3.7.3.exe` which is the 32-bit version.

If you want the 64-bit version, you have to go through quite some gymnastics: Find the "Looking for Python with a different OS?" text and then click on "Windows" and then find and click the " Windows x86-64" download.

It happened to me a few times that I installed the 32-bit version by accident and it's also not obvious since the 32-bit version file has a generic name and no "32" or anything in its filename.

Is there perhaps a way to reach out to the python.org people and give them that feedback?

**Comment by matthew-brett** [comment]
I guess Python.org folks have thought long and hard about this.   @zooba - sorry to send this ping out to you - but do you know why the Python.org downloads default to 32-bit?  It must have a cost in terms of performance, and it does make it harder for us wheel-builders.

**Comment by riddell-stan** [comment]
Anaconda's download page puts 64-bit first and the (unlabeled) "Download" button downloads 64-bit: https://www.anaconda.com/distribution/#download-section This would suggest doing so can't be causing that many problems for a reasonably diverse category of Python users with modern computers.

**Comment by TkTech** [comment]
Excellent @matthew-brett, I did not realize the pypi stats were on BigQuery 👍

**Comment by zooba** [comment]
There are still a decent number of 32-bit only Windows users (based on Microsoft telemetry, not the python.org downloads), and the "default option" ought to work for them. And 32-bit processes work just fine on 64-bit Windows, which means everybody gets a working download.

(That said, the Store package only has 64-bit. I'm waiting for complaints before adding a 32-bit package there, but haven't heard any yet :) )

The 32-bit version has a few advantages, even on a 64-bit OS (mostly lower memory usage), so I wouldn't expect it to go away. Certainly not for any current releases (e.g. if 3.8 was the first version to not provide 32-bit builds then you'll have to wait until all other versions are gone before finding any benefit). But if we get to a point where 32-bit Windows is no longer present then eventually the 32-bit builds will disappear.

**Comment by tstenner** [comment]
I've rebuilt @TkTech's excellent docker image for GCC 9.1.0, you can find it at [dockerhub](https://hub.docker.com/r/tstenner/manylinux/) or just pull `tstenner/manylinux:gcc9.1.0`.

**Comment by anthrotype** [comment]
@tstenner @TkTech I wonder if you could update your tstenner/manylinux:gcc9.1.0 docker image so that it supports Python 3.8?
https://travis-ci.org/fonttools/skia-pathops/builds/618707554

**Comment by anthrotype** [comment]
@tstenner @TkTech sorry if I insist.. Perhaps have you published a Dockerfile for tstenner/manylinux:gcc9.1.0 somewhere, that I can adpat to use the latest manylinux1 with support for python3.8? Thanks in advance

**Comment by YannickJadoul** [comment]
@anthrotype You should just be able to take [@TkTech's dockerfile](https://github.com/pypa/manylinux/issues/118#issuecomment-472380364), and rebuild that. Since the `manylinux1` docker images now contain Python 3.8, just rebuilding and getting the newer images as base should work.

**Comment by anthrotype** [comment]
ah! thanks, it was in this very thread and I missed that :)

**Comment by TkTech** [comment]
I'm attempting to automate it with Github Actions so in the future new images should become available any time manylinux or gcc have a release.

**Comment by mayeut** [comment]
This has been possible in manylinux2014 for quite some time now (gcc 10 toolchain). Older images are EOL (and manylinux_2_24 is deprecated) too will close this one.
