### ISSUE TITLE
Document musllinux in README

### ISSUE THREAD

**Issue by mayeut** [pypa/manylinux#1192]
As mentioned in https://github.com/pypa/manylinux/pull/1135#issuecomment-922366826 & https://github.com/pypa/manylinux/pull/1135#issuecomment-922725120, musllinux should be documented in the README file.

**Comment by ofek** [comment]
Any update on this?

**Comment by tyteen4a03** [comment]
+1 - currently confused on how to bring musllinux support to my packages.

**Comment by ofek** [comment]
Use https://github.com/pypa/cibuildwheel

**Comment by TonyXiang8787** [comment]
@mayeut Is this still relevant? I am thinking about to contribute on this. But I have doubts if the name of the repository itself needs to be changed. Otherwise you have `musllinux` image inside a repository called `manylinux`, which can be confusing.

**Comment by auvipy** [comment]
> `musllinux`

I think you didn't get it properly. it was talking about musllinux support
