### ISSUE TITLE
Rename the default branch to "main"

### ISSUE THREAD

**Issue by DiddiLeija** [pypa/manylinux#1193]
Hi, I have noticed that most of the pypa repositories have changed its default branch to `main`. Would you like to do the same with this repository?

**Comment by DiddiLeija** [comment]
What do you think about this proposal?

**Comment by mayeut** [comment]
done.

`master` is now named `main`

If you have a local clone, you can update it by running:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by DiddiLeija** [comment]
Thanks @mayeut!
