### ISSUE TITLE
openssl dev package is missing

### ISSUE THREAD

**Issue by wavenator** [pypa/manylinux#1195]
The image does not contain any OpenSSL headers. As I reviewed the Dockerfile and the build script, I saw that libssl-dev is being installed inside `install-build-packages.sh` before it is being removed in `build-openssl.sh`. Inside `build-openssl.sh`, the install command uses `make install_sw`, which does not install the header files (I think). I don'tThere's no way to tell whether this is intentional, but it makes it much harder to compile packages that require LibSSL (which is available in most existing Linux distributions). Is there a particular reason behind this decision?

**Comment by mayeut** [comment]
@wavenator, per the README:
> Development packages for all the libraries that PEP 571/599 list. One should not assume the presence of any other development package.

It's a bit outdated now that PEP600 is there but principles are the same. It can also be read as "Development packages for all the libraries whitelisted by auditwheel". There's a good reason for OpenSSL not to be whitelisted: there has been many API/ABI incompatible versions in the last few years & with 3.0.0 just released, those incompatibilities are not going away just yet.

Beside that, we don't want to expose our own build of OpenSSL:
- The version used might change overnight to deal with python build requirements itself. That's an implementation detail we don't want to expose as it will break downstream builds the day that version changes.

If OpenSSL is a direct dependency of your build, IMHO, you should rebuild it from sources as a static library (see https://github.com/pyca/cryptography, https://github.com/scikit-build/cmake-python-distributions wheel build for example).
