### ISSUE TITLE
musllinux_1_1: C++ toolchain broken?

### ISSUE THREAD

**Issue by ax3l** [pypa/manylinux#1242]
Hi,

I am trying out the new `quay.io/pypa/musllinux_1_1_x86_64` image from #1135 but the C++ compiler does not yet seem to work: https://github.com/pypa/manylinux/pull/1135#discussion_r770139003

I tried compiling a simple `c++`/`g++` hello world with this image.

It looks like `g++` is not fully set up yet:
```console
$ c++ main.cpp
ld: cannot find -lm
collect2: error: ld returned 1 exit status
```

I searched for a `libm` in the `/` dir and cannot find one. Adding `-static` also does not solve the problem.

Is something still missing for C++ builds in this base image? :)
cc @lkollar

**Comment by mayeut** [comment]
not sure what's going on with your build...
libm.a is provided as an empty archive file on musl systems (everything is in the libc shared library).
```
bash-5.0# file /usr/lib/libm.a
/usr/lib/libm.a: current ar archive

bash-5.0# cat main.cpp 
#include <math.h>

int main(int argc, char* argv[])
{
   return (int)log(atof(argv[1]));
}
bash-5.0# c++ main.cpp -lm
bash-5.0# ./a.out 1.0
bash-5.0# echo $?
0
bash-5.0# ./a.out 2.72
bash-5.0# echo $?
1
bash-5.0# c++ main.cpp
bash-5.0# ./a.out 1.0
bash-5.0# echo $?
0
bash-5.0# ./a.out 2.72
bash-5.0# echo $?
1
```

**Comment by ax3l** [comment]
Everything works now! I think my problem was about a week old. Thanks! :)
