### ISSUE TITLE
cmake does not find python libraries for pypy3.8 in manylinux_2014_x86_64 container

### ISSUE THREAD

**Issue by rkaminsk** [pypa/manylinux#1246]
I have a project using sci-kit build and recently cmake does not find pypy's C library anymore. It was working before though. Does anyone have an idea what the problem could be? I added a successful/failing run below.

Successful run ([success.log.txt](https://github.com/pypa/manylinux/files/7786272/success.log.txt)):

```
-- Found PythonInterp: /opt/_internal/pypy3.8-7.3.7/bin/python (found version "3.8.12")
-- Found PythonLibs: /opt/_internal/pypy3.8-7.3.7/bin/libpypy3-c.so (found suitable version "3.8.12", minimum required is "3.6")
```

Failing run ([fail.log.txt](https://github.com/pypa/manylinux/files/7786269/fail.log.txt)):
```
-- Found PythonInterp: /opt/_internal/pypy3.8-7.3.7/bin/python (found version "3.8.12")
CMake Error at /tmp/pip-build-env-mlugewr1/overlay/lib/pypy3.8/site-packages/cmake/data/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
Could NOT find PythonLibs (missing: PYTHON_LIBRARIES) (found suitable
version "3.8.12", minimum required is "3.6")
```

**Comment by mayeut** [comment]
Without more information than that, It's hard to guess what's changed and what might be the issue.
Do you know what's changed between the two runs ?

**Comment by rkaminsk** [comment]
I think it is because of changes in the `manylinux2014_x86_64` container. Did anything regarding pypy change recently?

**Comment by mayeut** [comment]
nothing

**Comment by mayeut** [comment]
Having the dates of the failing/successful builds might at least help to know what's changed by looking at the commits.

**Comment by rkaminsk** [comment]
Nothing regarding the build setup changed. There were some updated pip dependencies but also no major changes. Then, I should probably try to pin the dependencies to what was used in the successful build and see if this works...

**Comment by rkaminsk** [comment]
In fact, downgrading to setuptools version 59.4.0 instead of using the latest version 60.2.0 fixes the problem. Not sure where to best ask for further help how to get it running with the latest version. By chance any ideas? Otherwise, I think this can be closed here.

**Comment by mayeut** [comment]
Given you found where to ask for help about his, closing here.
