### ISSUE TITLE
How to run dockers images as containers

### ISSUE THREAD

**Issue by TungKaiYing** [pypa/manylinux#1257]
Hello i'm trying to run docker images as containers in background.

But each time the dockers containers is canceled in few seconds here the output of 

```
root@localhost:~/pyrig# docker run -d quay.io/pypa/manylinux2014_x86_64
8d95eacd2122b7d058950e6491f5345294a2a40a04a346c795d1352150ad2858
root@localhost:~/src# docker ps -l
CONTAINER ID   IMAGE                               COMMAND                  CREATED         STATUS                     PORTS     NAMES
266a0a54c3a3   quay.io/pypa/manylinux2014_x86_64   "manylinux-entrypoin…"   8 seconds ago   Exited (0) 7 seconds ago             practical_darwin
```

Help is welcome :)

Regards

**Comment by mayeut** [comment]
This is generic docker behavior and depending what you want to achieve, you might have better luck asking for help on docker forum.
You can start with:
```
docker run -d quay.io/pypa/manylinux2014_x86_64 bash -c "while true; do sleep 60; done"
```
It will stay in the background and you might be able to interact via `docker exec`/`docker cp`.
