### ISSUE TITLE
Any plans for dropping Python 3.6?

### ISSUE THREAD

**Issue by DiddiLeija** [pypa/manylinux#1260]
Hiya!

As you may know, Python 3.6 died in the last month. So, is there a plan for dropping support for this, or should we wait a little more to avoid breaking things?

**Comment by mayeut** [comment]
There's no plan for this yet and I think it will take some time before there's one given the high usage of python 3.6 at the moment (both by producers & consumers). All the relevant information not to drop it yet is in the linked issue.
All I can say for now is that it will probably happen before RH8 EOL (2029-06) and Ubuntu 18.04 EOL (2028-05) but probably not before Ubuntu 18.04 end of standard support (2023-05).

**Comment by henryiii** [comment]
FYI, might be nice to pin this, as it's something people might look for.
