### ISSUE TITLE
Python.h:44:10: fatal error: crypt.h: No such file or directory

### ISSUE THREAD

**Issue by MarshalX** [pypa/manylinux#1264]
Image: manylinux_2_24
Additional installed packages: libxml2
Error:
```
/opt/python/cp37-cp37m/include/python3.7m/Python.h:44:19: fatal error: crypt.h: No such file or directory
     #include <crypt.h>
                       ^
    compilation terminated.
```
About the issue: https://bugs.gentoo.org/802210
Resolved Python issue: https://bugs.python.org/issue44751

Question: Does Python in manylinux images include this fix?

**Comment by MarshalX** [comment]
I found bpo-44751 in changelogs of 3.10 and 3.11 only 

3.10 - https://docs.python.org/3.10/whatsnew/changelog.html#id12
3.11 - https://docs.python.org/3.11/whatsnew/changelog.html#id32

**Comment by vstinner** [comment]
> Upd. My new question is "Is it possible to fix building for 3.8 and 3.7?". I can confirm that on Python 3.10 the error is gone.

Sadly, Python 3.7 and 3.8 no longer accept bugfixes: https://devguide.python.org/#status-of-python-branches

You have to backport this change downstream (yourself).

**Comment by MarshalX** [comment]
@vstinner thank you

**Comment by vstinner** [comment]
Can't you backport the change in the manylinux_2_24 image?

**Comment by MarshalX** [comment]
@vstinner Did I understand correctly that we are talking about pull request to manylinux with patch applying for cpython inside the image?

**Comment by vstinner** [comment]
> @vstinner Did I understand correctly that we are talking about pull request to manylinux with patch applying for cpython inside the image?

Yes.

**Comment by mayeut** [comment]
@MarshalX, I do understand that the python header should not be included the crypt.h header in the first place however I fail  to understand how it's an issue for manylinux images (being 2_24 or others) as we do provide the header:
```
manylinux % docker run -it --rm quay.io/pypa/manylinux_2_24_x86_64:latest
root@15e76d6a79df:/# find / -name 'crypt.h'
/usr/local/include/crypt.h
root@15e76d6a79df:/# cd root/
root@15e76d6a79df:~# echo -e "#include <crypt.h>\nint main() { return 0; }\n" > test.c
root@15e76d6a79df:~# gcc test.c 
root@15e76d6a79df:~# ./a.out 
root@15e76d6a79df:~# echo $?
0
```

**Comment by mayeut** [comment]
no feedback since last comment, closing.
please re-open if needed.

**Comment by xmanners** [comment]
Very sad story, sadness from the center of country QAQ
