### ISSUE TITLE
devtoolset-11 for manylinux_2014

### ISSUE THREAD

**Issue by TonyXiang8787** [pypa/manylinux#1266]
Last year we had the upgrade to devtoolset-10 for manylinux_2014 see #1141 and #1155.

Now the devtoolset-11 is also released for CentOS 7. See below:
https://centos.pkgs.org/7/centos-sclo-rh-x86_64/devtoolset-11-toolchain-11.0-3.el7.x86_64.rpm.html

Maybe it is time to upgrade again? The C++20 support can be more improved.

**Comment by mayeut** [comment]
I started a rebuild of devtoolset-11 for i686 and reached out to clefos maintainer to do the same for s390x

**Comment by mayeut** [comment]
devtoolset-11-gcc is missing on aarch64: https://bugs.centos.org/view.php?id=18393

**Comment by mayeut** [comment]
Given devtoolset-11-gcc is still missing on aarch64, This won't be done. For those that don't need aarch64 or accept having a different toolset for aarch64, this can be manually installed with yum on x86_64.
