### ISSUE TITLE
patchelf is much slower since #1237

### ISSUE THREAD

**Issue by manthey** [pypa/manylinux#1290]
I noticed a significant performance penalty when building some complex wheels with `manylinux2014_x86_64` after #1237 was merged.  Specifically, this shows up on libraries where patchelf has to be invoked many times.

It is caused by the patchelf now at `/usr/local/bin/patchelf` actually being a python script that loads the python interpreter and then forwards the arguments to the actual patchelf binary.  The bulk of the time is spent invoking the python interpreter.  The actual patchelf wheel has the binary in some internal location (discoverable by doing something crude like `find /opt -name 'patchelf' -type f -size +10000c`).  If you link `/usr/local/bin/patchelf` to this binary, the speed is restored.

Maybe the actual binary should be linked appropriately (assuming doing so doesn't add too much extra maintenance).

For my use case, fully 15% of the total build time is being spent in invoking the python interpreter to run patchelf.

**Comment by mayeut** [comment]
This should be fixed by the `patchelf` update that will happen tomorrow.

**Comment by mayeut** [comment]
@manthey, can you confirm the performance regression is gone with latest images ?

**Comment by manthey** [comment]
Yes, I confirm the performance regression is gone.  Thank you.
