### ISSUE TITLE
Can you enable shared library on linux 2014 ?

### ISSUE THREAD

**Issue by TungKaiYing** [pypa/manylinux#1325]
Hello i wonder why python is not built with shared library enabled in manylinux 2014 ? That should be amazing to have it !

**Comment by mayeut** [comment]
This is done intentionnaly for building wheels which is the use-case of manylinux images.
c.f. https://github.com/pypa/manylinux/issues/255#issuecomment-450761634 & #30 for more details.

**Comment by TungKaiYing** [comment]
I've made my own python build thx your stuff is usefull to build python script that will be compatible with most of Linux old glibc distribution with pyinstaller thanks
