### ISSUE TITLE
Add PyPy support to musllinux

### ISSUE THREAD

**Issue by link2xt** [pypa/manylinux#1344]
#1134 added support for musl, but explicitly skips PyPy for musllinux BASE_POLICY. Any reason for that?

Alpine Linux has pypy packages, so it seems nothing should prevent building PyPy with musl.

**Comment by mayeut** [comment]
> Any reason for that?

We do not build PyPy ourselves and rely on binary packages provided by the PyPy project for manylinux.
The build process for PyPy is more complex and much longer than for CPython.
If PyPy starts providing builds for musl 1.1 then we can use that.
