### ISSUE TITLE
Manylinux_2_31 based on Ubuntu 20.04

### ISSUE THREAD

**Issue by sevagh** [pypa/manylinux#1363]
Hello,

In my fork of manylinux, I was able to add manylinux_2_31, based on Ubuntu 20.04: https://github.com/pypa/manylinux/compare/main...sevagh:manylinux:feat/add-manylinux_2_31-ubuntu20.04

I got the hint from this repo: https://github.com/mayeut/pep600_compliance#acceptable-distros-to-build-wheels 

The ubuntu 20.04 manylinux_2_31 container seems to be working well for my use case (within ciduilwheel), although I'm not sure pypa intends to use Ubuntu 20.04 for manylinux_2_31 in their own plans.

Is there a manylinux_2_31 coming soon? Is Ubuntu 20.04 acceptable as the base distro for it? Should I contribute my PR?

**Comment by mayeut** [comment]
There's no plan to add a manylinux_2_31 image to this repo.
The manylinux_2_24 (Debian based) showed that we can't have (easily) a debian based distro with an up-to-date toolchain like we have on RHEL based distros.
