### ISSUE TITLE
Update swig to 4.1.0

### ISSUE THREAD

**Issue by jschueller** [pypa/manylinux#1400]
I have no clue how to update these hashes: https://github.com/pypa/manylinux/blob/main/docker/build_scripts/requirements-tools/swig
cc @mayeut

**Comment by mayeut** [comment]
> I have no clue how to update these hashes:

c.f. https://github.com/pypa/manylinux#updating-the-requirements

Anyway, it will be picked up by the weekly automatic update tomorrow so there's nothing to do except to wait for a couple of days.
