### ISSUE TITLE
OpenBLAS cannot be found by pkg-config

### ISSUE THREAD

**Issue by vhaasteren** [pypa/manylinux#1482]
This may be related to [this scipy issue](https://github.com/scipy/scipy/issues/16308). My Python package requires scipy. However, when trying to build the package with (python -m build), it turns out that the blas library cannot be found.

First of course tried a `yum install -y openblas-devel`

Full output below:

[root@5b483ecc5dbe /]# python3.10 -m pip install scipy
Collecting scipy
  Downloading scipy-1.10.1.tar.gz (42.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.4/42.4 MB 37.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      The Meson build system
      Version: 1.1.0
      Source dir: /tmp/pip-install-2hoxu3sl/scipy_1a369e84062c41a59732e5f05ae60f94
      Build dir: /tmp/pip-install-2hoxu3sl/scipy_1a369e84062c41a59732e5f05ae60f94/.mesonpy-ojytqqsl/build
      Build type: native build
      Project name: SciPy
      Project version: 1.10.1
      C compiler for the host machine: cc (gcc 8.3.1 "cc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)")
      C linker for the host machine: cc ld.bfd 2.30-55
      C++ compiler for the host machine: c++ (gcc 8.3.1 "c++ (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)")
      C++ linker for the host machine: c++ ld.bfd 2.30-55
      Cython compiler for the host machine: cython (cython 0.29.34)
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Compiler for C supports arguments -Wno-unused-but-set-variable: YES
      Compiler for C supports arguments -Wno-unused-function: YES
      Compiler for C supports arguments -Wno-conversion: YES
      Compiler for C supports arguments -Wno-misleading-indentation: YES
      Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
      Library m found: YES
      Fortran compiler for the host machine: gfortran (gcc 8.3.1 "GNU Fortran (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)")
      Fortran linker for the host machine: gfortran ld.bfd 2.30-55
      Compiler for Fortran supports arguments -Wno-conversion: YES
      Checking if "-Wl,--version-script" : links: YES
      Program cython found: YES (/tmp/pip-build-env-4r3c975u/overlay/bin/cython)
      Program python found: YES (/usr/local/bin/python3.10)
      Found pkg-config: /usr/bin/pkg-config (0.23)
      Program pythran found: YES (/tmp/pip-build-env-4r3c975u/overlay/bin/pythran)
      Run-time dependency threads found: YES
      Library npymath found: YES
      Library npyrandom found: YES
      Found CMake: /usr/local/bin/cmake (3.23.3)
      WARNING: CMake Toolchain: Failed to determine CMake compilers state
      Run-time dependency openblas found: NO (tried pkgconfig and cmake)
      Run-time dependency openblas found: NO (tried pkgconfig and cmake)
      
      ../../scipy/meson.build:134:7: ERROR: Dependency "OpenBLAS" not found, tried pkgconfig and cmake
      
      A full log can be found at /tmp/pip-install-2hoxu3sl/scipy_1a369e84062c41a59732e5f05ae60f94/.mesonpy-ojytqqsl/build/meson-logs/meson-log.txt
      + meson setup --prefix=/opt/_internal/cpython-3.10.6 /tmp/pip-install-2hoxu3sl/scipy_1a369e84062c41a59732e5f05ae60f94 /tmp/pip-install-2hoxu3sl/scipy_1a369e84062c41a59732e5f05ae60f94/.mesonpy-ojytqqsl/build --native-file=/tmp/pip-install-2hoxu3sl/scipy_1a369e84062c41a59732e5f05ae60f94/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by mayeut** [comment]
which image are you using ? getting gcc Red Hat 8.3.1-3 seems strange at first glance.

**Comment by rgommers** [comment]
This doesn't look related to manylinux. The `openblas.pc` file is missing from `openblas-devel` I think (it definitely is missing in Fedora, so probably that translates to CentOS/RHEL), and as a result SciPy can't find OpenBLAS. I've seen this error a lot outside of manylinux images. And it's indeed an instance of [scipy#16308](https://github.com/scipy/scipy/issues/16308) it looks like.

**Comment by vhaasteren** [comment]
True as that may be, that does mean that pypa and anyone using cibuildwheel in continuous integrations cannot use SciPy. That's such a big and fundamental package in the scientific community that this essentially means that scientific projects cannot distribute wheels

Isn't there a workaround @rgommers ? (to be fair, I tried & failed) Or is this really just outside of the scope of pypa?

**Comment by rgommers** [comment]
I don't think that conclusion is correct. This matters only for building SciPy itself, not for installing SciPy. And there are wheels for all of the most common platforms on https://pypi.org/project/scipy/, so installation of those is trivial. And in case you need to build SciPy from source on a more niche platform, there are a couple of ways to get this to work - see for example the docs in http://scipy.github.io/devdocs/building/blas_lapack.html. And you can install any build dependency separately with a customization when using `cibuildwheel`, with something like this in `pyproject.toml`:
```
[tool.cibuildwheel.macos]
before-build = "bash {project}/tools/wheels/cibw_before_build_macos.sh {project}"
```

> Or is this really just outside of the scope of pypa?

There is still a "we should make use of pkg-config better" topic, yes - that is possible and in principle in scope for the Python packaging community, and I'd like to work on that at some point. But there's a lot of other things to do as well, and this one isn't top of the list - I'm not aware of anyone actively working on it.

**Comment by vhaasteren** [comment]
I see, yes you are right. Ok, thank you very much!

**Comment by mayeut** [comment]
not a manylinux issue

**Comment by basnijholt** [comment]
That's a great idea! Here's a suggested response format for the GitHub issue:

```markdown
For future reference, I solved this by modifying my meson.build file to not rely solely on pkg-config for finding OpenBLAS. Here's the working solution:

```meson
# Try multiple methods to find OpenBLAS
openblas_dep = dependency('openblas', required: false)
if not openblas_dep.found()
    # Fallback to manual detection
    openblas_dep = c_compiler.find_library('openblas', required: false)
endif

if openblas_dep.found()
    # OpenBLAS includes both BLAS and LAPACK
    blas_dep = declare_dependency(dependencies: [openblas_dep])
    lapack_dep = declare_dependency(dependencies: [openblas_dep])
else
    # Fall back to separate BLAS and LAPACK
    blas_dep = c_compiler.find_library('blas', required: true)
    lapack_dep = c_compiler.find_library('lapack', required: true)
endif
```

This works because while the pkg-config files might be missing on some systems, the libraries themselves are still available and can be found through direct library detection.

For cibuildwheel users, make sure to install the necessary packages:
```toml
[tool.cibuildwheel.linux]
before-all = "yum install -y openblas-devel"
```

**Comment by basnijholt** [comment]
For future reference, I solved this by modifying my meson.build file to not rely solely on pkg-config for finding OpenBLAS. Here's the working solution:

```meson
# Try multiple methods to find OpenBLAS
openblas_dep = dependency('openblas', required: false)
if not openblas_dep.found()
    # Fallback to manual detection
    openblas_dep = c_compiler.find_library('openblas', required: false)
endif

if openblas_dep.found()
    # OpenBLAS includes both BLAS and LAPACK
    blas_dep = declare_dependency(dependencies: [openblas_dep])
    lapack_dep = declare_dependency(dependencies: [openblas_dep])
else
    # Fall back to separate BLAS and LAPACK
    blas_dep = c_compiler.find_library('blas', required: true)
    lapack_dep = c_compiler.find_library('lapack', required: true)
endif
```

This works because while the pkg-config files might be missing on some systems, the libraries themselves are still available and can be found through direct library detection.

For cibuildwheel users, make sure to install the necessary packages:
```toml
[tool.cibuildwheel.linux]
before-all = "yum install -y openblas-devel"
```
