### ISSUE TITLE
does manylinux2014 support C++17 and C++20 ？

### ISSUE THREAD

**Issue by wbzzx-bb** [pypa/manylinux#1493]
in manylinux2014 docker image, devtoolset-10 does not change libstdc++.so.6, so it's still libstdc++.so.6.0.19 which is belong to listdc++-4.8.5, so can manylinux 2014 support C++17 and C++20 or not?

**Comment by mayeut** [comment]
yes, manylinux2014 can support C++17 & C++20 as the toolchain uses [GCC 10](https://gcc.gnu.org/projects/cxx-status.html#:~:text=C%2B%2B20%20Support%20in%20GCC&text=C%2B%2B20%20features%20are,%2Dstd%3Dgnu%2B%2B20%20.)

The toolchain uses static linking for features that were not present in libstdc++.so.6.0.19 to keep compatibility with vanilla EL 7 systems.

**Comment by wbzzx-bb** [comment]
I'd like to take an example to express my confuse, here is a piece of code that uses C++14 features:

```
#include <string>
#include <iterator>
#include <algorithm>
#include <iostream>

int main()
{
    std::string foo {"hello world10m"};
    foo.erase(std::find(std::cbegin(foo), std::cend(foo), '1'), std::cend(foo));
    std::cout << foo << std::endl;
}
```
compile it in manylinux2014 docker image, I got errors like this:

```
> g++ -std=gnu++14 -o test wbtest.cpp
wbtest.cpp: In function 'int main()':
wbtest.cpp:9:79: error: no matching function for call to 'std::basic_string<char>::erase(__gnu_cxx::__normal_iteror<const char*, std::basic_string<char> >,std::basic_string<char>::const_iterator)'
```

since the code use c++14 features and I got an error when compile it in manylinux2014 docker images, so I'm not sure it can support C++14 well or not. and also manylinux2014 use libstdc++.so.6.0.19 (belong to listdc++-4.8.5) it must miss some C++14/C++17 features, so in my opinon, manylinux2014 docker images cannot support all c++14/17 features  now


> yes, manylinux2014 can support C++17 & C++20 as the toolchain uses [GCC 10](https://gcc.gnu.org/projects/cxx-status.html#:~:text=C%2B%2B20%20Support%20in%20GCC&text=C%2B%2B20%20features%20are,%2Dstd%3Dgnu%2B%2B20%20.)
> 
> The toolchain uses static linking for features that were not present in libstdc++.so.6.0.19 to keep compatibility with vanilla EL 7 systems.
