### ISSUE TITLE
New manylinux images on aarch64 cause a segmentation fault when building python-isal.

### ISSUE THREAD

**Issue by rhpvorderman** [pypa/manylinux#1545]
Hi, the latest aarch64 image is causing segmentation faults when building [python-isal](https://github.com/pycompression/python-isal)

The newest x86_64 images work without issue.

`quay.io/pypa/manylinux2014_aarch64:2023-10-03-72cdc42` is the image currently used. I simply reverted to `quay.io/pypa/manylinux2014_aarch64:2023-09-17-ae90a16` which works fine.

This is the error output:
```
...
  ../../../project/tests/test_zlib_compliance.py::CompressObjectTestCase::test_decompress_unused_data PASSED [ 68%]
  ../../../project/tests/test_zlib_compliance.py::CompressObjectTestCase::test_decompresscopy SKIPPED [ 68%]
  Fatal Python error: Segmentation fault
  
  Current thread 0x00000055013338e0 (most recent call first):
    File "/project/tests/test_zlib_compliance.py", line 432 in test_decompressmaxlen
...
...
 /bin/bash: line 240:  2413 Segmentation fault      (core dumped) env HOSTNAME=506ed24d94c4 SSL_CERT_FILE=/opt/_internal/certs.pem OLDPWD=/ LC_ALL=en_US.UTF-8 LD_LIBRARY_PATH=/opt/rh/devtoolset-10/root/usr/lib64:/opt/rh/devtoolset-10/root/usr/lib:/opt/rh/devtoolset-10/root/usr/lib64/dyninst:/opt/rh/devtoolset-10/root/usr/lib/dyninst:/usr/local/lib64 PATH=/tmp/tmp.UTzGcKo38I/venv/bin:/opt/python/cp38-cp38/bin:/opt/rh/devtoolset-10/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin *** LANG=en_US.UTF-8 CIBUILDWHEEL=1 SHLVL=1 AUDITWHEEL_ARCH=aarch64 DEVTOOLSET_ROOTPATH=/opt/rh/devtoolset-10/root HOME=/root LANGUAGE=en_US.UTF-8 AUDITWHEEL_PLAT=manylinux2014_aarch64 PKG_CONFIG_PATH=/usr/local/lib/pkgconfig AUDITWHEEL_POLICY=manylinux2014 _=/usr/bin/env PIP_DISABLE_PIP_VERSION_CHECK=1 PIP_ROOT_USER_ACTION=ignore PYTHON_ISAL_BUILD_CACHE=True PYTHON_ISAL_BUILD_CACHE_FILE=/tmp/build_cache CFLAGS='-g0 -DNDEBUG' sh -c 'pytest -v /project/tests/test_igzip.py /project/tests/test_gzip_compliance.py /project/tests/test_zlib_compliance.py /project/tests/test_igzip_lib.py -k '"'"'not test_compress_decompress'"'"''
 ```
 
This might be my code. This might be the code for ISA-L. Fact is it only happens with the newer image. It might be some GCC bug as well. 

I was wondering if you could give me some pointers how I could pinpoint this problem, so the core problem can be resolved.

**Comment by mayeut** [comment]
You can first find which is the first image tag that fails.
The diff between last working tag & first failing tag might give an insight if this is related to a change in the manylinux repo.
One thing that happens with every update is system package update so, you can dump the list of packages to check versions between the 2 images & find which update causes the issue.

**Comment by rhpvorderman** [comment]
It magically solved itself on the latest release, and I forgot to close this issue. Thanks!
