### ISSUE TITLE
Can we upgrade gcc 11.x in manylinux2014?

### ISSUE THREAD

**Issue by ratan-prasad** [pypa/manylinux#1551]
Can we install gcc 11.x  in manylinux2014, will it break/violate manylinux2014 rules? Do you foresee any issue in such upgrade of gcc version?
Do I need to take care of anything else in this case?

**Comment by mayeut** [comment]
Duplicates https://github.com/pypa/manylinux/issues/1266 / https://github.com/pypa/manylinux/pull/1269
However it seems that the toolset is now available for aarch64 so I might give this another go.

**Comment by mayeut** [comment]
> However it seems that the toolset is now available for aarch64 so I might give this another go.

I was mistaken , closing as duplicate of #1266
