### ISSUE TITLE
Include uv in tools?

### ISSUE THREAD

**Issue by henryiii** [pypa/manylinux#1607]
I'd like to try uv for cibuildwheel, and it's a single binary that works across Python versions, so it seems like adding it here would be a good first step. Thoughts?

Also, uv already supports free-threaded builds since https://github.com/astral-sh/uv/pull/2805. :)

**Comment by mayeut** [comment]
How do you plan to install it on Windows/macOS ?
I'd rather use pipx to install the binary (as it allows to track version changes easily without rewriting a specific update script) but this is not possible at the moment c.f. https://github.com/astral-sh/uv/issues/3439

**Comment by henryiii** [comment]
I think this is fixed for the next release?

**Comment by mayeut** [comment]
> I think this is fixed for the next release?

for gnu aarrch64, it seems to be but not for musllinux_1_1, I'll create an issue tomorrow.

**Comment by henryiii** [comment]
It looks like Rust doesn't support 32-bit musl with host tools (only without), and 64-bit musl is based on 1.2: https://doc.rust-lang.org/rustc/platform-support.html

**Comment by henryiii** [comment]
I'm working on the first part here: https://github.com/astral-sh/uv/pull/3523

It also needs the other archs. I notice muslllinux is completely missing from the readme, is that intentional?

**Comment by mayeut** [comment]
> is that intentional?

no, this is #1192

**Comment by henryiii** [comment]
I'm not sure Rust has enough support for the special musl archs, see https://github.com/astral-sh/uv/pull/3537. Would it be acceptable to add it for everything but those? I expect they are very lightly used.

**Comment by henryiii** [comment]
uv muslllinux 1.1 wheels shipped. Only musllinux powerpc64le and s390x are missing now. Those are likely going to be tricky, though powerpcle64 might be the easier of the two.

**Comment by henryiii** [comment]
musl ppc64le was doable.
