### ISSUE TITLE
Vault repos for 2014 image

### ISSUE THREAD

**Issue by sumerc** [pypa/manylinux#1664]
Hi,

I started getting few days ago, because CentOS reached EOL.

```
14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
```

Is there any ongoing work for this?

Thanks,

**Comment by mayeut** [comment]
duplicate of https://github.com/pypa/manylinux/issues/1641 that's been fixed.
Is your image up-to-date ?

**Comment by sumerc** [comment]
Sorry.

I used a wrong tag for testing. Confirmed this works with latest.
