### ISSUE TITLE
tk/tckl pkg-config broken on manylinux2014

### ISSUE THREAD

**Issue by mattip** [pypa/manylinux#1718]
PR #1365 added support for tk/tcl 8.6, and removes the static stub libraries. But using pkg-config still has the stub libraries in the link command
```
# pkg-config tcl --libs
-L/usr/local/lib -ltcl8.6 -ltclstub8.6

 pkg-config tk --libs
-L/usr/local/lib -ltk8.6 -ltkstub8.6 -ltcl8.6 -ltclstub8.6
```

I am not sure how the cpython build works around this. I ran into this when I tried to use the pkg-config command to build tkinter for PyPy.

**Comment by mayeut** [comment]
These should be private to the cpython builds of manylinux2014. I'll check if/how I can remove all of this from /usr/local.

**Comment by mattip** [comment]
Heh, don't hide it too much, I use it on PyPy :). FWIW, I fixed this by removing the missing stub static libs from the pkgconfig config file. Would you like a PR?
```
sed -i -e"s/ -ltclstub8.6//" /usr/local/lib/pkgconfig/tcl.pc
sed -i -e"s/ -ltkstub8.6//" /usr/local/lib/pkgconfig/tk.pc
```

**Comment by mayeut** [comment]
If this is fixed for now on your end, I guess it can wait for the merge of manylinux_2_34 at the end of the week. Almost all scripts are being reworked so I'd rather have this one included in the existing PR.

**Comment by mattip** [comment]
Ahh, cool 097ccb7384648bed56 fixes this. Closing.
