### ISSUE TITLE
Publish manylinux images to Docker Hub as well?

### ISSUE THREAD

**Issue by ncoghlan** [pypa/manylinux#181]
The baseline manylinux images are currently published to the PyPA account on quay.io (the registry acquired initially by CoreOS, and then subsequently by Red Hat when they acquired CoreOS).

The one downside to this is that it requires using a fully qualified image name, including the `quay.io` registry identifier.

Might it make sense to also publish the images to the PyPA account on Docker hub as well?

At the moment, that just includes a few Warehouse related images: https://hub.docker.com/u/pypa/

(Tagging @ewdurbin and @dstufft, as I assume any requests for push access would need to go through them)

**Comment by ncoghlan** [comment]
Note: the question in the issue title is a genuine one. My motivation was the fact that I initially looked for the pre-built images there, and assumed there weren't any for a while, until @njsmith mentioned them existing, and then I noticed the correct registry reference in the README.

So the benefit of pushing them to both registries is hopefully making it easier for folks to find them, but the downside is that we'd have two names for the same sets of artifacts.

**Comment by ncoghlan** [comment]
Let's put this in the "not needed" category for now.

I except most folks will end up consuming one of the wheel building helper projects rather than accessing the images directly, and the authors of those projects already know to find the manylinux reference images on quay.io.

**Comment by tangowithfoxtrot** [comment]
@njsmith, Would publishing to both Docker Hub and quay.io still be an option? I'd be willing to update the build workflow to make it happen if that's agreeable.
