### ISSUE TITLE
failed to deploy i686 image

### ISSUE THREAD

**Issue by njsmith** [pypa/manylinux#189]
After merging #188, the i686 image upload failed:

https://travis-ci.org/pypa/manylinux/jobs/373722003

Not sure what's going on here.

CC: @trishankatdatadog

**Comment by trishankatdatadog** [comment]
That sucks :( Let me take a look ASAP...

**Comment by trishankatdatadog** [comment]
Ok, I think I know what's going on, but I'm surprised that not all of commits in that PR was merged. Hrm. Let me take a look...

**Comment by trishankatdatadog** [comment]
Oh, my bad, I forgot to commit :doh: Coming shortly...

**Comment by trishankatdatadog** [comment]
Should be fixed in #190, let's see...

**Comment by njsmith** [comment]
#190 seems to have worked!

https://travis-ci.org/pypa/manylinux/builds/374041049

Thanks for the quick follow-up there!
