### ISSUE TITLE
wget https broken in manylinux images

### ISSUE THREAD

**Issue by dvarrazzo** [pypa/manylinux#202]
See [this build failure](https://travis-ci.org/psycopg/psycopg2-wheels/jobs/382886588):

```
+ wget https://github.com/openssl/openssl/archive/OpenSSL_1_0_2o.tar.gz
--2018-05-23 17:13:33--  https://github.com/openssl/openssl/archive/OpenSSL_1_0_2o.tar.gz
Resolving github.com... 192.30.253.113, 192.30.253.112
Connecting to github.com|192.30.253.113|:443... connected.
OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Unable to establish SSL connection.
```

**Comment by mayeut** [comment]
I guess `wget` is the system one, using the system `OpenSSL` which does not support a recent enough TLS protocol version. This is a common problem these days...
If you can switch to `curl`, it should fix your issue. It's been rebuilt from sources in the `manylinux` image using `OpenSSL 1.0.2o`.

**Comment by dvarrazzo** [comment]
No wait: don't remove wget. curl gets stuck more than 50% of time on ftp. Sigh.

https://travis-ci.org/psycopg/psycopg2-wheels/builds/382907565

**Comment by trishankatdatadog** [comment]
Does anyone else have reservations about this? The problem is that we don't know what this will break downstream until we break it. I think it's harmless to leave `wget` in unless it becomes a security problem.

**Comment by mayeut** [comment]
This issue has been opened for almost a year, closing it. Please reopen if needed.

`wget` is not installed anymore on manylinux images. Please use `curl`.
