### ISSUE TITLE
Provide a 32-bit docker image

### ISSUE THREAD

**Issue by njsmith** [pypa/manylinux#21]
I guess it would be good at some point to provide a 32-bit `manylinux1` image.

Actually arranging this will be a pain in the butt, because we'll definitely want to share build scripts between the 32-bit and 64-bit builds, but docker has a strong idea that every docker "build context" must be totally self-contained. Like, you're not even allowed to symlink out of it, because that would be bad. Maybe this will get better in the future, but AFAICT right now the *only* way to make this work reasonably well given docker + quay.io's limitations is:

* Make git repository git-common for the actual build scripts
* Make git repository git-64 for the 64-bit Dockerfile, and include git-common as a git submodule
* Make git repository git-32 for the 32-bit Dockerfile, and include git-common as a git submodule
* Make quay.io repository quay-64 pointing at git repository git-64, and have it trigger a rebuild whenever there's a commit to git-common or git-64
* Make quay.io repository quay-32 pointing at git repository git-32, and have it rebuild whenever there's a commit to git-common or git-32

In theory the git-64 and git-32 repositories could be the same, with the Dockerfiles in different subdirectories. But we'd still need git-common to be separate (so that it could be checked out into both subdirectories), and we'd still need quay-64 and quay-32 to be separate so that users can specify which docker image they want to pull.

[Hopefully in the future quay.io will start allowing different Dockerfiles to share an overlapping build context ([currently impossible - hopefully they'll update this doc page if that changes :-)](https://docs.quay.io/issues/cannot-locate-dockerfile.html)), and then we could combine all the git repositories into one git repo that feeds multiple quay.io repos.]

This is all doable enough, I guess. The biggest hassle is that getting CI working will be difficult with everything spread out over multiple repos.

**Comment by rmcgibbo** [comment]
I don't think the repo organization is the hardest part of this. We can always `wget` the scripts or whatever.

**Comment by njsmith** [comment]
Yeah, it took me a while to figure out everything above, but it's doable enough -- the CI is the only part I'm really nervous about (b/c I want pull-requests to the common-scripts repo to trigger tests of all the docker repos, and pull-requests to the docker repos to also test just that repo), and even that is just a Simple Matter of Scripting.

One thing that might help make the CI part simpler would be to move the actual tests into the end of the Dockerfile build, so that you just can't build a broken docker image.

**Comment by njsmith** [comment]
On further thought, the other option that would be worth considering is doing the actual builds on Travis and then `docker push`ing them to quay.io via Travis's deploy machinery. That simplify the repo and CI, plus give us more control over tags (I think).

**Comment by rmcgibbo** [comment]
That's a good idea. It would give us more control but keep the automatic-deploy-on-commit feature.

**Comment by rmcgibbo** [comment]
Done now. It is working [here](https://github.com/manylinux/python-manylinux-demo) too. One note for posterity is that you really need to prefix your bash script with the command `linux32` (i.e. `linux32 bash` or `linux32 bash /path/to/script.sh`), which changes the environment so that uname says "32-bit" and is necessary for `yum` (and I think `distutils`) to correctly detect that you want 32-bit stuff.
