### ISSUE TITLE
How should we arrange the docker image namespace?

### ISSUE THREAD

**Issue by njsmith** [pypa/manylinux#22]
There are repositories, and tags within those repositories, and it's all a bit confusing.

I'm currently inclined towards making multiple repositories: `pypa/manylinux1_x86_64`, `pypa/manylinux1_i686` (and then later maybe there will be `pypa/manylinux2_x86_64`, etc.), and avoiding routine use of any tags except `latest`.

But, as previously stated, I have no idea what I'm doing with docker, so would welcome any thoughts :-)

**Comment by rmcgibbo** [comment]
I agree to avoid using tags other than latest. What's the problem with putting two `Dockerfile`s (32 and 64 bit) in the same repository though, and building them with Docker. Especially given that I expect them to share most of their code, having them in the same repository seems easier to me.

**Comment by njsmith** [comment]
Sorry, in my original post all mentions of "repository" mean docker repository, not git repository.

So we'd have 1 git repository (yes), and then a travis.yml that does something like `cd docker; docker build -f Dockerfile-64; docker build -f Dockerfile-32`, and pushes the two images to the two different docker repositories.

**Comment by rmcgibbo** [comment]
Okay, I think that's basically what  I've done in #23. I don't know how to do the deploy part though.

**Comment by rmcgibbo** [comment]
This is done now, so I'm closing this.
