### ISSUE TITLE
Rebuild image and update system packages to address RHSA-2018:2602

### ISSUE THREAD

**Issue by trishankatdatadog** [pypa/manylinux#222]
Quay reports that the `manylinux1` image available at the time of writing is vulnerable to the L1TF issue:

https://quay.io/repository/pypa/manylinux1_x86_64/manifest/sha256:596ea8447c214139df019fd4ca6ad9bd3890c79a998cefc4bbab348c40850e40?tab=vulnerabilities

I believe we only need to rebuild a new image and upload to Quay using Travis.

@njsmith Do you have privileges to do this?

**Comment by njsmith** [comment]
I'm actually not sure how to trigger a rebuild other than to push an empty commit, which i guess anyone can do?

**Comment by trishankatdatadog** [comment]
Yeap, unfortunately, the update seems to be available on Red Hat, but not Centos, as I suspected.

It's really not the biggest issue in the world (threat model assumes attackers can run code on the same machine that runs the container), but this is a good reminder that we need to move away from Centos 5 sooner than later!

**Comment by mayeut** [comment]
Closing the issue since it cannot be fixed.
