### ISSUE TITLE
std::string is the wrong size

### ISSUE THREAD

**Issue by ibell** [pypa/manylinux#234]
TL;DR : When I do ``sizeof(std::string)`` in C++ in a manylinux container, I get 8, whereas on a modern ubuntu 18.04 distro, I get 32.  

This means that the binaries built in a manylinux container cannot be linked against in Cython, rather defeating part of the point of manylinux wheels.  The Cython thread that lead to this conclusion is here: https://groups.google.com/forum/#!topic/cython-users/BwCk-WHEZag and the salient bit from the thread is this:

Inside the manylinux docker image, I did:
```
[root@34b9be38936f /]# g++ --version
g++ (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
[root@34b9be38936f /]# head -n 30 so.cpp
#include <string>
#include <iostream>
int main(){
  std::cout << sizeof(std::string) << std::endl;
}
[root@34b9be38936f /]# g++ so.cpp && ./a.out
8
```
and outside, on my normal g++ 7.3, I get:
```
ian@ian-ThinkPad-X220:~$ g++ --version
g++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
ian@ian-ThinkPad-X220:~$ head so.cpp
#include <string>
#include <iostream>
int main(){
  std::cout << sizeof(std::string) << std::endl;
}
ian@ian-ThinkPad-X220:~$ g++ so.cpp && ./a.out
32
```

Any idea how to fix this?

**Comment by jdemeyer** [comment]
Personally, I wouldn't consider this a bug in manylinux. I don't see how manylinux can fix these C++ ABI issues. If part of your build was done with manylinux, all of it should be done with manylinux.

**Comment by ibell** [comment]
The unfortunate answer then is that I can't ensure ABI compatibility between the Python module that is built inside the manylinux container and the other package built outside the container that links with the package coming from manylinux :( .  That is a real pity, because the manylinux wheels are key for CI testing, where rebuilding packages can timeout your builds entirely.  

I can see the point that I could also build my parent package inside the docker container, but that's pretty inconvenient, especially in the case of CI, where getting docker running inside the CI instance can be a non-starter.

On Travis CI, you can fall back to an ancient ubuntu (14.04) which uses a compiler that is ABI compatible with the manylinux build.  Accidentally I made that choice some time ago, and I only got bit by this issue just now.

**Comment by njsmith** [comment]
Oh, wait, is this a class that you're exporting from one python package and then importing for another, separately distributed python package? And the second package is trying to directly access the internal C++-level fields of the first package?

If so, then yeah, that's not going to work... It means you need to somehow guarantee that these two packages that are being built at different times, under different circumstances, use the same C++ ABI. But as you've discovered, C++ ABIs are not that stable. One case is this issue with the gcc's Linux C++ ABI change in 2015, but I think there are other changes like this as well, e.g. if one package is built using clang and the other is built using gcc, and I'm pretty sure you can have similar issues on Windows if your packages get built by different versions of MSVC.

Can you remove the use of `std::string` from your public / cross-package api? Maybe use python strings or `char*` instead?

**Comment by rdb** [comment]
> I can see the point that I could also build my parent package inside the docker container, but that's pretty inconvenient, especially in the case of CI, where getting docker running inside the CI instance can be a non-starter.

It's not clear to me why you consider this a non-starter.  It sounds completely reasonable to me to build your parent package inside the manylinux container.  Running docker in CI services is a very common practice, and in fact there are many CI services nowadays that even exclusively use docker.

**Comment by njsmith** [comment]
> The unfortunate answer then is that I can't ensure ABI compatibility between the Python module that is built inside the manylinux container and the other package built outside the container that links with the package coming from manylinux :(

You can force the more recent compiler to use the old ABI by passing `-D_GLIBCXX_USE_CXX11_ABI=0`. But that's not even your biggest problem.

Your problem is that when you *distribute* these two packages, you have no way to control how your end users build them. Maybe they'll get one of them from a wheel, and the other from conda. Or one from a wheel, and build the other themselves. Or build them both themselves, but at different times when they have different compiler versions installed. If they were distributed together as a single package, it wouldn't be a problem – whichever compiler was used would be consistent across the whole package. But with two different packages, you don't know that. That's why I'm suggesting to remove the use of `std::string` from your package's public, external API.

**Comment by ibell** [comment]
Hmm, I can see the point about using native python types (which internally map to C types, rather than C++ types), as you then have a better shot of ABI compatibility.  Is it guaranteed if you use Python/C types that you will have ABI compatibility?  

I have avoided that in the past because I find the alphabet soup of bytes/str/unicode in python 2/3 to be a bridge too far for my little brain.

**Comment by ibell** [comment]
Well, in my case I switched my ``std::string`` for a ``bytes``, let's see how that plays out.  That makes the public API all python types, which should work much nicer I hope.

**Comment by njsmith** [comment]
>  Is it guaranteed if you use Python/C types that you will have ABI compatibility?

Yes, it's guaranteed that within a single Python interpreter, everyone agrees on how python and C types are laid out in memory.
