### ISSUE TITLE
manylinux docker image bash segfault w/ recent kernel

### ISSUE THREAD

**Issue by proppy** [pypa/manylinux#254]
Just a quick note that recent version (>=4.15.9) of linux seems to break manylinux docker image:
See https://github.com/dockcross/dockcross/issues/249 and https://github.com/CentOS/sig-cloud-instance-images/issues/62 https://github.com/CentOS/sig-cloud-instance-images/issues/103 and https://github.com/moby/moby/issues/28705#issuecomment-262226229

Adding `vsyscall=emulate` to the cmdline seems to workaround the issue, should we add something about this to the `README.md`?

**Comment by rdb** [comment]
See #158.

**Comment by proppy** [comment]
Thanks for the pointer, closing!
