### ISSUE TITLE
Add standard build directories to LD_LIBRARY_PATH?

### ISSUE THREAD

**Issue by matthew-brett** [pypa/manylinux#26]
Should we add `/usr/local/lib:/usr/local/lib64`to `LD_LIBRARY_PATH` by default?

I notice openblas, for example, builds to `/usr/loca/lib`.

**Comment by rmcgibbo** [comment]
Are those not directories that are searched by default, regardless of `LD_LIBRARY_PATH`?

**Comment by rmcgibbo** [comment]
Perhaps not.

http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html

> Many Red Hat-derived distributions don't normally include /usr/local/lib in the file /etc/ld.so.conf. I consider this a bug, and adding /usr/local/lib to /etc/ld.so.conf is a common ``fix'' required to run many programs on Red Hat-derived systems.

Actually, it might be a better idea to get rid of the LD_LIBRARY_PATH and add everything to /etc/ld.conf instead. It's less likely for a user to mess that up.

**Comment by njsmith** [comment]
+1 to adding to ld.so.conf

**Comment by matthew-brett** [comment]
Should probably add

```
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/lib64/pkgconfig
```

**Comment by rmcgibbo** [comment]
Would there be a conf file for pkg_config too?

**Comment by matthew-brett** [comment]
If so I don't know what the conf file is.

**Comment by njsmith** [comment]
@matthew-brett: now that we have some more experience with building wheels here, do you think this is still an issue?

**Comment by matthew-brett** [comment]
Yes - for now I have been fixing it in https://github.com/matthew-brett/manylinux-builds/blob/master/common_vars.sh#L15 - but it would good not to have to do this.

**Comment by ogrisel** [comment]
Feel free to have a look at #45.
