### ISSUE TITLE
Where is zlib stored in this docker image?

### ISSUE THREAD

**Issue by endrebak** [pypa/manylinux#296]
I get the error
```
fatal error: zlib.h: No such file or directory
     #include <zlib.h>
```

running this command:

`gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DWITHNUMPY -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -IlibBigWig -I/opt/_internal/cpython-3.6.8/include/python3.6m -I/opt/_internal/cpython-3.6.8/lib/python3.6/site-packages/numpy/core/include -I/opt/_internal/cpython-3.6.8/include/python3.6m -c libBigWig/bwStats.c -o build/temp.linux-x86_64-3.6/libBigWig/bwStats.o`

How do I need to update my include paths to successfully build my wheel?

**Comment by mayeut** [comment]
zlib is not part of the [manylinux1](https://www.python.org/dev/peps/pep-0513/#the-manylinux1-policy) or [manylinux2010](https://www.python.org/dev/peps/pep-0571/#the-manylinux2010-policy) policies.
As such, its development package is not installed.
2 options are available:
1. Rebuild zlib from latest sources
2. Install the `zlib-devel` package with `yum` (this one has not received security updates for some time on manylinux1).

**Comment by njsmith** [comment]
See also: https://github.com/pypa/auditwheel/issues/152

**Comment by endrebak** [comment]
Yum install worked. Thanks!
