### ISSUE TITLE
drop 3.4? and what about 2.7?

### ISSUE THREAD

**Issue by Synss** [pypa/manylinux#310]
According to [PEP 429](https://www.python.org/dev/peps/pep-0429/), Python 3.4 has reached its end of life on March.

Do you have a schedule to actively drop it?

By the way, what about 2.7 by the end of the year?

Or is the idea to stop maintaining manylinux1 when manylinux2010 is ready and see then?

**Comment by mayeut** [comment]
I guess there's no reason to drop python 3.4 / 2.7 as long as they do not prevent updates.
For Python 3.4, it'll probably be either `OpenSSL` (1.0.2 is EOL at the end of the year, we'll switch to 1.1.1, not supported by python 3.4) or `pip`.

**Comment by Synss** [comment]
Thank you for the answer! That is fine and not totally unexpected. I guess I will drop versions on my (downstream) side even though they would technically still build and run.


Merci Matthieu ;)
