### ISSUE TITLE
Python 3.8

### ISSUE THREAD

**Issue by minrk** [pypa/manylinux#313]
Issue to track adding Python 3.8 to the images, which it looks like should happen at the end of July, with 3.8.0b3.

From the [release notes for 3.8b1](https://www.python.org/downloads/release/python-380b1/), 3.8 ABI is planned to be frozen in beta 3, which is [scheduled](https://www.python.org/dev/peps/pep-0569/) for 2019-07-29.

Or maybe the policy in this repo should be freezing the ABI with release candidates? That would give a much shorter window for developers to start publishing wheels with this tool (3 weeks vs 3 months).

**Comment by filipArena** [comment]
I think beta versions should be part of the images.
