### ISSUE TITLE
Update Auditwheel in 2010 image?

### ISSUE THREAD

**Issue by matthew-brett** [pypa/manylinux#323]
I'm trying to get Multibuild working smoothly with Manylnux2010:

https://github.com/matthew-brett/multibuild/issues/238

It would be a great help if we could update Auditwheel to latest master, to allow Auditwheel to automatically detect the Manylinux platform:

https://github.com/pypa/auditwheel/pull/151

Is that acceptable?  Happy to do a PR.

**Comment by lkollar** [comment]
`auditwheel` has been upgraded to 2.1 in the image. Can you check if this fixes your issue?

**Comment by takluyver** [comment]
The requested upgrade has happened, so I'll close this.
