### ISSUE TITLE
auditwheel is cloned from less-official repo

### ISSUE THREAD

**Issue by merwok** [pypa/manylinux#33]
The manylinux/auditwheel repo was copied to pypa/auditwheel, but the build script in this pypa/manylinux repo still clone from manylinux/auditwheel. Right now they are synchronized, but it would feel more official to clone from the pypa repo, and would allow removing the other repo later.

**Comment by rmcgibbo** [comment]
Good idea. It would probably just pull auditwheel for pypi really though.

**Comment by njsmith** [comment]
Fixed by gh-42
