### ISSUE TITLE
Import 3.8 GPG pubkey once and for all into repo

### ISSUE THREAD

**Issue by trishankatdatadog** [pypa/manylinux#361]
Instead of [downloading the 3.8 GPG pubkey over and over again](https://github.com/pypa/manylinux/blob/61d3701b703c8f5166267292e39bbe154536fb9c/docker/build_scripts/build_utils.sh#L97-L98), we should provide a trusted copy here once and for all.

**Comment by mattip** [comment]
What is the gpg or curl incantation to provide a trusted copy, we can then add it to the image?

**Comment by trishankatdatadog** [comment]
@mattip I mean we download the pubkey from say Keybase, write it as an ASCII file to this repo, then we simply `gpg --import` it in the build script rather than downloading the key over and over again (open to [attacks on SKS](https://gist.github.com/rjhansen/67ab921ffb4084c865b3618d6955275f)).

**Comment by mattip** [comment]
@trishankatdatadog can you be a little more specific? What do we do to "download the pubkey from say Kebase"? Is there a link?

**Comment by trishankatdatadog** [comment]
I was told it's [here](https://keybase.io/ambv/pgp_keys.asc?fingerprint=e3ff2839c048b25c084debe9b26995e310250568)
