### ISSUE TITLE
Security patches in manylinux

### ISSUE THREAD

**Issue by JonasVautherin** [pypa/manylinux#421]
I am not an expert in security, but I was wondering about manylinux: the whole point of manylinux being to use old versions of libraries in order to be compatible with most distributions, doesn't that bring security issues?

One of the reasons for updating a library is to get security patches, right? If I link my code against an old version of, say, libc, and that one has a security issue, then I get it in my code, don't I?

How does manylinux deal with that? Is there a way to patch those libraries anyway? That would sound like maintaining an old fork, and probably would require resources... 

Or is it just not a problem at all?

**Comment by rdb** [comment]
manylinux provides you the environment to compile your library against an old version of libc.  The aim of this is to ensure that your library doesn't depend on symbols that are only present in very recent versions of libc.

However, your library won't *contain* any libc code, it will still only link to libc.  Whenever someone imports your library on a different system, it uses their *system* version of libc, which may be more recent and may have security patches applied.

**Comment by JonasVautherin** [comment]
Oh, right. Seems obvious now :laughing:. Thanks a lot!
