### ISSUE TITLE
Drop support for CPython 3.4 (manylinux1/manylinux2010)

### ISSUE THREAD

**Issue by mayeut** [pypa/manylinux#427]
CPython 3.4 has reached end-of-life in march 2019

**Comment by rdb** [comment]
This need not be a reason to keep support, but I'm just pointing out for the record that Ubuntu Trusty ships with Python 3.4 and won't be EOL until April 2022.

**Comment by mayeut** [comment]
More details on Trusty EOL:
"standard" support for Trusty ended in April 2019.
There is in fact an extended paid support until April 2022 and thus EOL is mentioned as April 2022.
https://wiki.ubuntu.com/Releases

Python 3.4 keeps us from updating some python packages (or we'd need a specific requirement file) as well as upgrading OpenSSL (1.0.2 series is EOL) leading to potential security issues.

**Comment by lkollar** [comment]
I second this. We have several version upgrade PRs failing because of Python 3.4. We should just remove it.

**Comment by mayeut** [comment]
Reopen => manylinux1
