### ISSUE TITLE
Drop support for CPython 2.7 (manylinux2010)

### ISSUE THREAD

**Issue by mayeut** [pypa/manylinux#428]
CPython 2.7 has reached end-of-life in January 2020

**Comment by lkollar** [comment]
This could impact many users, but I wonder if we could tag the last image still shipping with 2.7 and keep it around as a fallback for users who still need it?

**Comment by rdb** [comment]
CPython 2.7 won't be EOL until April 2020:
https://www.python.org/psf/press-release/pr20191220/

**Comment by lkollar** [comment]
We could create and tag the last image once Python 2.7.18 is released during PyCon just so that users have the last version available.

**Comment by mayeut** [comment]
Since end of january, all images are tagged so tagging => OK
Once Python 2.7.18 is released, we'll update to get the proper tag then drop python 2.7.

**Comment by hugovk** [comment]
Python 2.7.18 has been released in April! 🚀

**Comment by pradyunsg** [comment]
Whenever we're ready. ;)

**Comment by mayeut** [comment]
@pradyunsg,

The question would be "whenever package maintainers are ready".
After digging around some stats for different subjects around `manylinux`, I'm not so sure they are...

I'll write something here but please tell me if it's better suited for https://discuss.python.org/c/packaging.

I made some stats on all latest release of projects producing manylinux wheels, active (having at least 1 release in the past year) and for which at least 1 manylinux wheel has been downloaded over the past month. As with all stats, it might be biased by my process and/or interpretation.
I checked some metrics for projects having their latest release going back 12 months, 6 months, 3 months & 1 month.

Here are some interesting numbers regarding python versions:

  | 12 months | 6 months | 3 months | 1 month
-- | -- | -- | -- | --
number of projects with manylinux wheels | 2007 | 1543 | 1109 | 608
cp26 | 0,1% | 0,1% | 0,1% | 0,2%
cp27 | 26,1% | 22,4% | 22,3% | 20,9%
cp33 | 0,1% | 0,0% | 0,0% | 0,0%
cp34 | 5,0% | 2,5% | 2,3% | 2,8%
cp35 | 47,8% | 45,8% | 44,3% | 42,3%

For those still building for cp26/cp33, they are using custom images as tagging every manylinux image in quay.io occurred after those versions were dropped. For those building for cp34, they might be using a tagged manylinux image.

As for cp27, if all those package maintainers are using a single image workflow and still want to maintain cp27, this will lead to roughly 500 package build workflow that will need to be reworked.

Personnaly, no doubt about dropping cp27 but, even though this issue has been opened for almost a year, I doubt package maintainers have seen it (maybe announcing on https://discuss.python.org/c/packaging has better visibility ?)

**Comment by mayeut** [comment]
`cp27` is dropping more and more, time to remove it in `manylinux2010`, part of #877 effort.

More stats there: https://mayeut.github.io/manylinux-timeline/

We'll probably wait for the summer to drop support for `manylinux1` altogether.

**Comment by mayeut** [comment]
CPython 2.7 dropped on manylinux2010 by merging #993

Last image with CPython 2.7 is tagged `2021-02-06-3d322a5`
