### ISSUE TITLE
Update from OpenSSL 1.0.2? to OpenSSL 1.1.1? (manylinux1 / manylinux2010)

### ISSUE THREAD

**Issue by mayeut** [pypa/manylinux#429]
OpenSSL 1.0.2 has reached end-of-life in December 2019: https://mta.openssl.org/pipermail/openssl-announce/2019-December/000164.html
Keeping up with security updates requires to update to the 1.1.1 series (LTS). This requires [dropping CPython 3.4](https://github.com/pypa/manylinux/issues/427)

**Comment by lithammer** [comment]
Solved by https://github.com/pypa/manylinux/pull/439.
