### ISSUE TITLE
yum update failing on s390x image

### ISSUE THREAD

**Issue by lkollar** [pypa/manylinux#473]
To reproduce run `docker run --rm quay.io/pypa/manylinux2014_s390x:latest yum update`.

This will result in the following error:
```
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
https://download.sinenomine.net/clefos/7/sclo/s390x/rh/repodata/c705d44edae5e3f3e249c16d6c4a3ea855b716c4004d893944b6212f3e160585-primary.sqlite.bz2:
 [Errno 14] HTTPS Error 404 - Not Found
```
`yum` retries a few times but fails in the end.

Doing the same on the base image works fine:
`docker run  --rm s390x/clefos:7 yum update`

This is blocking auditwheel builds as the s390x jobs [fail](https://travis-ci.org/pypa/auditwheel/jobs/646315431?utm_medium=notification&utm_source=github_status) in Travis.

I think we just need to rebuild the s390x image to pick up the latest base image, but I'm not sure if this is possible without submitting and merging PR to trigger a build.

**Comment by lkollar** [comment]
I just realised it is possible to manually trigger jobs on the Travis UI so I started a build for the manylinux2014 images.

**Comment by mattip** [comment]
xref nealef/clefos#1.The repo in question seems to have intermittent problems.

**Comment by myselfhimself** [comment]
I may have a similar problem cause using Github Actions: https://github.com/myselfhimself/gmic-py/runs/433673433
Related source: 
- parent running script: https://github.com/myselfhimself/gmic-py/blob/master/build_tools.bash#L106
- child build wheels script: https://github.com/myselfhimself/gmic-py/blob/master/manylinux/build-wheels.sh#L6
I do not know what is the attempted host.

**Comment by lkollar** [comment]
Seems that `yum update` succeeds now but the Travis build environment doesn't have enough disk space now: https://travis-ci.community/t/no-space-left-on-device-for-system-z/5954/12

**Comment by mayeut** [comment]
Issues are gone for a while now so closing this.

**Comment by ashvardanian** [comment]
I'm experiencing the same issue in 2024... Just a week ago the GitHub CI passed just fine, now [it fails](https://github.com/ashvardanian/StringZilla/actions/runs/8120941587/job/22205963188). It fails on `yum update`, and can be easily reproduced with the command in the first post.

```sh
  Cannot find a valid baseurl for repo: clefos-rh/s390x
  Error: Command ['sh', '-c', 'yum update -y && yum install -y glibc-devel wget python3-devel'] failed with code 1. 
  ```
