### ISSUE TITLE
GCC version in manylinux2014_i686

### ISSUE THREAD

**Issue by seoester** [pypa/manylinux#474]
When trying to build `i686` wheels I ran into a problem as GCC did not accept the `-std=c++14` flag.

Upon checking I noticed that the manylinux2014_i686 image ships GCC v4.8.5 whereas manylinux2010_i686 already ships v7.3.1 and manylinux2014_x85_64 ships v8.3.1.

Is intentional or tracked in an issue that I missed?

**Comment by mayeut** [comment]
Fixed by #586
