### ISSUE TITLE
The base docker image is private

### ISSUE THREAD

**Issue by SylvainCorlay** [pypa/manylinux#481]
The base docker image of manylinux 2010 (quay.io/pypa/manylinux2010_centos-6-no-vsyscall) does not seem to be public.

Would it be possible to make this docker image pullable so that we can reproduce the manylinux 2010 docker image locally?

**Comment by mayeut** [comment]
You can rebuild the image by running the build scripts or by pulling a manylinux2010 and tagging the appropriate layer.
I'm not sure there's a reason to push this image. (It's not private,  it's not being pushed ever).

**Comment by SylvainCorlay** [comment]
Thanks, yes indeed, I was mislead by the fact that it was refered to by URL. I should have closed the issue.
