### ISSUE TITLE
auditwheel in venv?

### ISSUE THREAD

**Issue by pskopnik** [pypa/manylinux#483]
At the moment, auditwheel is installed globally within the Python 3.7 site-packages of the manylinux images.
This installation is easily accidentally broken due to the particular requirements of auditwheel: Recent versions of the wheel package break auditwheel.

Dependencies for building user packages seem to be commonly installed globally. That includes the demo: https://github.com/pypa/python-manylinux-demo/blob/master/travis/build-wheels.sh#L9
Whenever wheel is upgraded for the Python 3.7 installation, auditwheel breaks. This has happened in #336 and https://github.com/ijl/orjson/pull/56#discussion_r383255620.

Could the globally available auditwheel be installed in a venv? That would improve stability and be resilient to arbitrary pip installs by users as the frozen dependencies would remain unaffected.

**Comment by mayeut** [comment]
@pskopnik, that's a very good idea indeed. Are you willing to create a PR for that ?

**Comment by pskopnik** [comment]
Yes, I will prepare something this week :)

**Comment by lkollar** [comment]
@pskopnik How do you plan to make `auditwheel` available on the `PATH`? I think if we were to add the `bin` directory in the `venv` to `PATH` that would also expose the `python` and `pip` binaries which can be problematic. We could also consider something like [pipx](https://github.com/pipxproject/pipx).

**Comment by pskopnik** [comment]
No, I'm soft-linking auditwheel from `.../venv/bin` to `/usr/bin/`

**Comment by pskopnik** [comment]
pipx could be an alternative. But I have not encountered problems yet with the described approach for other Python executables (some testing of auditwheel is still required, could also be part of CI?). Presumably that's exactly what pipx does, plus additional ux and meta-data management.

**Comment by mayeut** [comment]
Done.
