### ISSUE TITLE
CMake requires libpythonXX.a

### ISSUE THREAD

**Issue by pitrou** [pypa/manylinux#484]
Not sure it's worth fixing here, but it seems that when using:
```cmake
find_package(Python3 COMPONENTS Interpreter Development REQUIRED)
```
the "Development" component fails being found if `libpythonXX.a` and `libpythonXX.so` both cannot be found. This is a problem when building C extensions using CMake (rather than using setuptools).

Note that the library isn't actually used for building (you can `touch` the missing file and it makes CMake happy), but it's required to be present anyway...

(see [CMake docs](https://cmake.org/cmake/help/v3.16/module/FindPython3.html))

**Comment by pitrou** [comment]
Also opened an issue against CMake: https://gitlab.kitware.com/cmake/cmake/issues/20425

**Comment by mayeut** [comment]
@pitrou,
it seems the bug you opened over at CMake has been fixed.
Can you confirm it's working please (or do we need to wait for CMake 3.18.0) ?

**Comment by pitrou** [comment]
I think this is going to wait for CMake 3.18.0. I don't see any mention of a backport in the CMake issue or PR.

**Comment by mayeut** [comment]
@pitrou,

CMake 3.18 is now available.
Can you confirm it's working please ?

**Comment by pitrou** [comment]
Sorry for the delay. I've tried CMake 3.18.2 and it does fix the issue, thank you.
