### ISSUE TITLE
The README implies Python 2.7 is supported in manylinux2014 but it isn't

### ISSUE THREAD

**Issue by exarkun** [pypa/manylinux#493]
> The images currently contain:
> CPython 2.7, 3.4, 3.5, 3.6, 3.7 & 3.8, installed in /opt/python/<python tag>-<abi tag>. The directories are named after the PEP 425 tags for each environment -- e.g. /opt/python/cp27-cp27mu contains a wide-unicode CPython 2.7 build, and can be used to produce wheels named like <pkg>-<version>-cp27-cp27mu-<arch>.whl.

However, the manylinux2014 image does not contain any Python 2.7 builds and cannot build Python 2.7 wheels.

**Comment by trishankatdatadog** [comment]
@mayeut we're not planning to support 2.7 anymore in manylinux2014, right? If so, do we just need a change in documentation?

**Comment by mayeut** [comment]
> we're not planning to support 2.7 anymore in manylinux2014, right?

Right, I don't see why to bother with the support of 2.7 on manylinux2014. It's EOL and never was in that image (i.e. not a regression)

> If so, do we just need a change in documentation? 

Yes. IMHO, I think we should clearly separate readme between branches with links to one another  (the readme in manylinux 2014 doesn't mention python 2.7)

**Comment by trishankatdatadog** [comment]
@exarkun please send a PR to fix this in the doc? Thanks!

**Comment by mayeut** [comment]
Python 2.7 dropped from manylinux2010 & manylinux2014 branch merged in master, README is now in sync for  manylinux2010 & manylinux2014 images.
