### ISSUE TITLE
Combining 32-bit and 64-bit

### ISSUE THREAD

**Issue by jakirkham** [pypa/manylinux#50]
Just as a thought, one could actually combine the functionality of these two images. See this [comment](https://github.com/conda-forge/conda-forge.github.io/issues/29#issuecomment-207667255) and this [Dockerfile](https://github.com/jakirkham/docker_centos_gcc/blob/centos_5/Dockerfile).

**Comment by ogrisel** [comment]
That means that we will have to rework the folders structure one more time however. But this is not a big deal as we can change the name of the image to just `manylinux1` or `manylinux1_intel` for instance.

**Comment by mayeut** [comment]
`i686` is getting less and less traction these days. Furthermore, the same toolchain does not exist on `manylinux2010` & `manylinux2014` so this would result in bigger images for most user. Also, as `manylinux` support more and more architectures, it now makes sense to keep them separate.
