### ISSUE TITLE
AppImages of manylinux Pythons

### ISSUE THREAD

**Issue by niess** [pypa/manylinux#538]
Hello,

this is not an issue but you might be interested in the following. I am producing AppImages of the manylinux `/opt/python` installs by relocating them from the Docker images. These AppImages can be used as isolated and self contained Python runtimes.

The corresponding GitHub project is [python-appimage](https://github.com/niess/python-appimage). The Python runtimes are available from the [releases](https://github.com/niess/python-appimage/releases).

**Comment by mayeut** [comment]
Thanks for the info but a better place for this is over at https://discuss.python.org

**Comment by niess** [comment]
@mayeut Thank you for the link and sorry for the spam :)
