### ISSUE TITLE
CMake 3 on aarch64, ppc64le and s390x

### ISSUE THREAD

**Issue by ax3l** [pypa/manylinux#544]
Hi,

can we add a recent CMake to the `ppc64le`, `aarch64` and `s390x` images?
While PyPI provides usable binary wheels for `i686` and `x86-64`, these less popular architectures currently have to build a recent CMake 3 from scatch.

Ref.: https://pypi.org/project/cmake/3.17.1/#files

**Comment by mayeut** [comment]
Hi, it'll probably benefit more people to ask for new wheels to be built over at  https://github.com/scikit-build/cmake-python-distributions (e.g. https://github.com/scikit-build/cmake-python-distributions/issues/96)  rather than only supplying this in a manylinux image no ?

**Comment by ax3l** [comment]
That would probably work if e.g. https://github.com/scikit-build/cmake-python-distributions/issues/96 considers switching the CD framework for something like `cibuildwheel`.

But on the other hand it makes sense to me to add a modern build system generator together with the modern C/C++ compilers in the manylinux images.
