### ISSUE TITLE
manylinux1_i686 uses linux_x86_64 tag

### ISSUE THREAD

**Issue by fbergmann** [pypa/manylinux#55]
hello, 

i was trying to use the quay.io/pypa/manylinux1_i686 container to build 32bit python binaries. However, unfortunately the wheels created were marked with the 

`Tag: cp*-cp*m-linux_x86_64`

(with `*` being the version being compiled against). Now I would have been expecting: 

`linux_i686`

is that supposed to happen?

thanks
Frank

**Comment by rmcgibbo** [comment]
Take a look at 
https://github.com/pypa/python-manylinux-demo.

In particular, you need to use the command "linux32" I think, which you see in the travis.yml file there.

**Comment by fbergmann** [comment]
thanks! that was it ...
