### ISSUE TITLE
Install cmake 2.8.11 by default?

### ISSUE THREAD

**Issue by ibell** [pypa/manylinux#57]
I need cmake to build my manylinux library and yumming it takes quite a bit of time.  Any chance of installing it in the the main image?

**Comment by matthew-brett** [comment]
You can get 2.8 fairly quickly with `yum install cmake28` : https://github.com/matthew-brett/manylinux-builds/blob/master/library_builders.sh#L72

**Comment by ibell** [comment]
"fairly quickly" is relative.  It's about 5 minutes for me from the base image.

**Comment by matthew-brett** [comment]
Ouch - that's strange - it's only 10M or so.  It's just a few seconds for me (on a good university internet connection).

**Comment by ibell** [comment]
It's odd, sometimes it's very fast, other times it takes minutes to install cmake.  Perhaps I'll have to fork your image, and add cmake permanently to my image.  It always has to update epel as well, which doesn't help...

**Comment by ibell** [comment]
Or rather, base/primary

**Comment by ibell** [comment]
nm, I can just derive my own docker image with cmake/cython installed.

**Comment by njsmith** [comment]
That seems like a good solution -- unfortunately we don't really have the bandwidth to try and sort every interesting development tool, so making this a base that people build on seems like a more scalable approach. Do let us know if you have any problems.

**Comment by matthew-brett** [comment]
That said - if you want to do a PR adding this line to `<manylinux>/docker/build_scripts/build.sh` then I am sure that would be welcome.

**Comment by ibell** [comment]
Done: https://github.com/pypa/manylinux/pull/58
