### ISSUE TITLE
32 bit manylinux 2010 image uses newer gcc, breaking packaging

### ISSUE THREAD

**Issue by mattip** [pypa/manylinux#570]
xref numpy/numpy#16146

PR gh-565 updated the gcc toolchain in the 32bit manylinux2010 images. It would be helpful if both toolchains were provided for a transitional period. In the mean time NumPy will pin the version of the manylinux image used to test and build.

**Comment by mayeut** [comment]
@mattip,
Very sorry for the inconvenience by the merge of the new devtoolset.
Hopefully, `yum install libgfortran4` shall resolve the issue you're seeing over at numpy.
I already tried to ldd openblas with that and seems fixed.
I will build numpy and push a fix if it resolves the issue (in roughly 12 hours).
Once again, sorry for the maintenance burden to all bumpy folks.

**Comment by mattip** [comment]
No problem, thanks for the fix. I will try a PR to add `yum install libgfortran4`
