### ISSUE TITLE
Question about pip

### ISSUE THREAD

**Issue by giampaolo** [pypa/manylinux#598]
Hello. Am not sure if this is the right place to ask this question so sorry in advance.
I / we want to provide wheels for psutil project:
https://github.com/giampaolo/psutil/pull/1758

As far as I understand, CentOS 6 is necessary in order to provide wheels that are as portable as possible, but unfortunately Travis CI only supports CentOS 7. As such, when the user runs `pip install psutil`, is pip clever enough to figure out whether to get the wheel or the tarball (based on available wheel names on PYPI I guess?)? If not, is there a way to do that manually (in setup.py?) as in:

```
if kernel_version > (something): 
    use_wheel() 
else:
    use_tarball()
```

Thanks in advance.

**Comment by mayeut** [comment]
The only thing that's being checked is glibc version
`>= 2.17` => `manylinux2014` wheel if available
`>= 2.12` => `manylinux2010` wheel if available
`>= 2.5` =>  `manylinux1` wheel if available
sources otherwise.

**Comment by giampaolo** [comment]
Thank you.
