### ISSUE TITLE
Add recent CMake and SWIG

### ISSUE THREAD

**Issue by HDembinski** [pypa/manylinux#659]
It would be great if the docker images came with a recent cmake and swig pre-installed, since these are fairly common dependencies for Python packages that need to be build.

**Comment by rdb** [comment]
Should this be closed, now that CMake is part of the manylinux2014 image?

**Comment by mayeut** [comment]
SWIG was requested as well and a recent CMake is not available on `manylinux2010` (this last one might not be an issue as `cmake` can easily be `pip` installed on `manylinux2010` which was not the case for `manylinux2014` "alt-arch"). I also hope to get some consistency in the tooling available across `manylinux` images with #877.

**Comment by mattip** [comment]
Is there a way to set up a tool like dependabot to semi-automate updates to the images when new versions of packages are released?

**Comment by mayeut** [comment]
I'm thinking of doing it through a custom GHA workflow https://github.com/pypa/manylinux/pull/918#issuecomment-751210207

**Comment by rdb** [comment]
Just out of curiosity, why was SWIG specifically included?  There are many binding generators for Python, and SWIG seems far from the most popular one.  Is there a criterium for libraries that are made available out-of-the-box?

**Comment by mayeut** [comment]
> There are many binding generators for Python, and SWIG seems far from the most popular one. Is there a criterium for libraries that are made available out-of-the-box?

A. You need to ask for it like @HDembinski did
B. Shall not be pip installable (i.e. takes a long time to build)
