### ISSUE TITLE
Linking to libpython.so (or not)

### ISSUE THREAD

**Issue by c-martinez** [pypa/manylinux#69]
First of all, apologies in advance -- I'm new to building wheels, so this might be a very basic question but...

I'm trying to build a manylinux wheel for [OpenCV](http://opencv.org/), but the OpenCV [build process](http://docs.opencv.org/master/d7/d9f/tutorial_linux_install.html#gsc.tab=0) for python, requires `PYTHON_LIBRARY` to be set to your `libpython<version>.so`.

As far as I understand, it is not recommended to link to libpython when building wheels. But what would be the alternative?

Is it the case that, as long as OpenCV links their library to `libpython`, it will not be possible to build a manylinux wheel for it?

**Comment by njsmith** [comment]
Have you tried pointing it to libpython.a?

**Comment by c-martinez** [comment]
I don't think there is a libpython.a on the manylinux docker images, unfortunately (I'm testing with quay.io/pypa/manylinux1_i686). I did try using `/usr/lib/libpython2.4.so`, but the resulting wheel is broken. Thanks for the suggestion anyway.

**Comment by matthew-brett** [comment]
Ouch.   I think VTK Python has the same problem - it links directly against the Python dynamic library, making it much harder to build wheels - see [this mailing list thread](http://vtk.1045678.n5.nabble.com/Fwd-OSX-build-links-directly-with-Python-binary-avoidable-td5731734.html).

In the longer term, I believe the correct fix is for the OpenCV build process to allow the Python symbols to be undefined at link time - see the thread above.   Do you know any OpenCV folks who could help out with the build?

**Comment by c-martinez** [comment]
Hmmm... I see... No, don't know any OpenCV folk directly, but perhaps they would be happy to see a PR. I'll see what I can do.

Thanks!

**Comment by njsmith** [comment]
Oh right, libpython.a was totally the wrong suggestion, sorry about that :-)

**Comment by c-martinez** [comment]
@njsmith - It was worth trying :-)

**Comment by blowekamp** [comment]
I stumbled on this issue. With regards to VTK there should be a patch for it:
https://gitlab.kitware.com/vtk/vtk/merge_requests/1511
