### ISSUE TITLE
autoconf version

### ISSUE THREAD

**Issue by reaperhulk** [pypa/manylinux#71]
The version of autoconf shipping with CentOS 5 is sufficiently out of date to prevent building various projects (among them libffi). It's easy to install it yourself, but since this seems likely to be a common problem for users of the manylinux1 image I'd be happy to send a PR to install the latest autoconf (2.69, released 4 years ago) as part of the build process if people think it belongs here.

(It really just looks like `RUN wget http://ftp.gnu.org/gnu/autoconf/autoconf-latest.tar.gz && tar zxvf autoconf-latest.tar.gz && cd autoconf* && ./configure && make install`)

**Comment by rmcgibbo** [comment]
Yes, I think this would be pretty widely useful, and wouldn't take up too much disk space.

**Comment by njsmith** [comment]
+1

Instead of a `RUN` of course it should go into the existing scripts, for the usual stupid docker layering reasons, and I suppose it would be good to check the sha256 like we do for other downloads.
