### ISSUE TITLE
manylinux builds will fail due to wheel changes

### ISSUE THREAD

**Issue by reaperhulk** [pypa/manylinux#736]
`wheel` released 0.35.x, which switches from using a `pep425tags` module to vendoring `pypa/packaging`. This breaks https://github.com/pypa/manylinux/blob/e1878836b69cd5aaff8c7b756a7363d6983f6b09/docker/build_scripts/python-tag-abi-tag.py#L5-L7
which is used during the image build. The fix here is probably to use packaging directly, but the API is significantly different so some investigation will be required to duplicate the behavior.

**Comment by reaperhulk** [comment]
To be clear, wheel is pinned so this will not instantly cause a failure, but upgrading wheel will require this fix.

**Comment by mayeut** [comment]
Thanks for the heads up.
The script has been updated. It now uses `packaging` vendored in wheel not to require 3 more packages to be installed, will be easy enough to move from `wheel` if needed.
