### ISSUE TITLE
newer openssl required by cryptography

### ISSUE THREAD

**Issue by yhager** [pypa/manylinux#74]
I'm trying to build cryptography using the docker image. The openssl version that is installed there is 0.9.8u, which generates the following error in cryptography:
```
$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from cryptography.hazmat.backends import default_backend
>>> default_backend()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py", line 35, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py", line 22, in _available_backends
    "cryptography.backends"
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 47, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 250, in <module>
    _verify_openssl_version(Binding.lib.SSLeay())
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 230, in _verify_openssl_version
    "You are linking against OpenSSL 0.9.8, which is no longer "
RuntimeError: You are linking against OpenSSL 0.9.8, which is no longer support by the OpenSSL project. You need to upgrade to a newer version of OpenSSL.
```

Running `yum install openssl` is unhelpful, as 0.9.8e is the latest that's available for Centos 5.

I noticed that the image build script already builds a newer openssl (for curl), but then deletes it. Maybe this can stay in the image and be available for modules like cryptography?

**Comment by njsmith** [comment]
Yes, you definitely shouldn't be trying to build your own manylinux wheels for cryptography using the centos 5 openssl.

/me sends up the @reaperhulk signal

**Comment by rmcgibbo** [comment]
> I noticed that the image build script already builds a newer openssl (for curl), but then deletes it. Maybe this can stay in the image and be available for modules like cryptography?

We did this deliberately because we don't want to be responsible. Your best bet is to download and compile OpenSSL from source.

**Comment by yhager** [comment]
@njsmith I need a manylinux cryptography wheel, and it's not available on pypi. What do you suggest my best course is?

@rmcgibbo, that's what I'm doing, but I was hoping the docker image would be a one-stop-shop for wheels making. I don't understand the liability stuff though.

**Comment by reaperhulk** [comment]
@yhager We're going to start shipping a manylinux1 cryptography wheel in the next month or so. I can put together a docker image that will be capable of it sooner than that though (it'll be based off the cffi work I did last week https://github.com/reaperhulk/cffi-manylinux1). Let me see what I can put together quickly here...

**Comment by yhager** [comment]
@reaperhulk that'll be awesome, thanks. No need to rush it, I'll be using my own cryptography wheel until then, built from openssl 1.0.2 that I built from source on the centos5 docker image.

**Comment by reaperhulk** [comment]
I went ahead and made a thing: https://github.com/reaperhulk/cryptography-manylinux1

Note that this doesn't try to handle the openssldir for specific distros, which means by default it won't have any trust roots for TLS. To fix this for your specific use case you can set the openssldir in the install_openssl script to whatever your distribution uses.

**Comment by njsmith** [comment]
...doh, I actually hit close by mistake. But I guess that's a reasonable status for this now. If anyone disagrees feel free to reopen or say so :-)

@yhager: it's not so much a liability issue. It's that if you are building a wheel that includes a copy of openssl, then you need to have some plan for how you are going to notice when openssl gets security fixes, and rebuild your wheel with the new version of openssl, and distribute it to everyone who got your old insecure wheel. So we don't provide openssl because (a) we don't want anyone to *accidentally* start shipping openssl without even noticing, and (b) our handling of openssl is adequate for our purposes, but might not work for everyone else's needs. Example: imagine heartbleed happened today. This would be a fairly low priority issue for us, because our openssl doesn't run servers. But if other people are using our openssl, then suddenly their emergency is our problem. It's generally bad if the people's whose pagers are going off are different from the people who can fix the problem, and we don't want to get ourselves into that situation.

**Comment by yhager** [comment]
@njsmith, Thanks for the detailed explanation, it makes a lot of sense. The issue can stay closed as far as I'm concerned.

**Comment by yhager** [comment]
@reaperhulk, Oh my, this must be the quickest turnaround I've ever seen. This is awesome. Thanks.

**Comment by njsmith** [comment]
Oh yeah, that openssldir thing is nasty.

I did a quick look to see how anaconda handles this. The relevant bug seems to be here: https://github.com/ContinuumIO/anaconda-issues/issues/137
...and the resolution seems to be that they decided to start shipping the certifi bundle and ignore the system trust store. And patch the openssl binaries at install time to point to the certifi install location. Soooooo probably not very helpful.

A simple option for cryptography would be to, in python, figure out where the system trust store is and then set the relevant envvars before loading openssl. The thing to worry about would be making sure that your settings are restricted just to your copy, though -- if libssl checks the envvars once at dlopen time then you're fine, you can just set the envvars temporarily while calling dlopen. If it checks then at runtime then things are harder...
