### ISSUE TITLE
Error bulding manylinux wheels requiring signalfd.h, pipe2, SOCK_NONBLOCK, O_CLOEXEC

### ISSUE THREAD

**Issue by vitaly-krugl** [pypa/manylinux#75]
I am attempting to build a manylinux wheel from the [nupic.core](https://github.com/numenta/nupic.core) project in github. I am using the docker image quay.io/pypa/manylinux1_x86_64. nupic.core builds and statically links against the [capnproto library](https://github.com/sandstorm-io/capnproto), which relies on signalfd.h by default. Unfortunately, the docker image quay.io/pypa/manylinux1_x86_64 does not provide  signalfd.h, so my build fails like this:

```
Linking CXX static library libkj.a
[ 27%] Built target kj
[ 29%] Building CXX object src/kj/CMakeFiles/kj-async.dir/async.c++.o
[ 30%] Building CXX object src/kj/CMakeFiles/kj-async.dir/async-unix.c++.o
/nupic.core/build/scripts/ThirdParty/Source/CapnProto/src/kj/async-unix.c++:36:26: fatal error: sys/signalfd.h: No such file or directory
 #include <sys/signalfd.h>
```

I even tried a capnproto-specific work-around to steer capnproto from using signalfd.h by setting `-DKJ_USE_EPOLL=0`. However, in that case, the build failed due to lack of other functions and constants (in glibc?):

```
/nupic.core/build/scripts/ThirdParty/Source/CapnProto/src/kj/async-io.c++: In member function ‘int kj::{anonymous}::SocketAddress::socket(int) const’:
/nupic.core/build/scripts/ThirdParty/Source/CapnProto/src/kj/async-io.c++:348:13: error: ‘SOCK_NONBLOCK’ was not declared in this scope
     type |= SOCK_NONBLOCK | SOCK_CLOEXEC;
             ^
/nupic.core/build/scripts/ThirdParty/Source/CapnProto/src/kj/async-io.c++:348:29: error: ‘SOCK_CLOEXEC’ was not declared in this scope
     type |= SOCK_NONBLOCK | SOCK_CLOEXEC;
                             ^
In file included from /nupic.core/build/scripts/ThirdParty/Source/CapnProto/src/kj/async-io.c++:24:0:
/nupic.core/build/scripts/ThirdParty/Source/CapnProto/src/kj/async-io.c++: In lambda function:
/nupic.core/build/scripts/ThirdParty/Source/CapnProto/src/kj/async-io.c++:648:38: error: ‘O_CLOEXEC’ was not declared in this scope
   KJ_SYSCALL(pipe2(fds, O_NONBLOCK | O_CLOEXEC));
                                      ^
/nupic.core/build/scripts/ThirdParty/Source/CapnProto/src/kj/async-io.c++:648:47: error: ‘pipe2’ was not declared in this scope
   KJ_SYSCALL(pipe2(fds, O_NONBLOCK | O_CLOEXEC));
```

I recursively grep'ed for these symbols in the docker image's `/usr/include/` directory, and they were all absent. 

Regarding `pipe2`, linux man has this to say:
> pipe2() was added to Linux in version 2.6.27; glibc support is available starting with version 2.9.

Regarding `signalfd`:
> signalfd() is available on Linux since kernel 2.6.22. Working support is provided in glibc since version 2.8. The signalfd4() system call (see NOTES) is available on Linux since kernel 2.6.27

**Comment by njsmith** [comment]
Unfortunately, there's nothing that the manylinux docker image can do about this -- the docker image follows the manylinux1 spec, and the manylinux1 spec says that code that requires `signalfd` or `pipe2` *has* to fail to build. At some point there will be a manylinux2, but not yet. In the mean time, since there's no todo item here, I'm going to close the bug report.

Some more discussion, including alternatives, here: https://mail.python.org/pipermail/wheel-builders/2016-July/000175.html
