### ISSUE TITLE
manylinux2014_ppc64le build failing on Travis CI

### ISSUE THREAD

**Issue by YannickJadoul** [pypa/manylinux#758]
Now that Travis CI seemed to have fixed some of the problems on its ppc64le platforms, I tried building the manylinux2014 again for inclusion in `cibuildwheel` (joerick/cibuildwheel#382), but somehow, [something still goes wrong](https://travis-ci.com/github/pypa/manylinux/jobs/379043095#L2972):

```
+ rm -rf /usr/local/share/man
rm: cannot remove ‘/usr/local/share/man’: Input/output error
```

Investigating and trying to ignore this error (see https://github.com/YannickJadoul/manylinux/commit/c2aa1e9b7abbb55162136d4499e1901c990a78a2), results in this failure being ignored, but [the following `rm` command fails](https://travis-ci.org/github/YannickJadoul/manylinux/jobs/724730853#L2873):

```
rm: cannot remove ‘build_scripts’: Input/output error
The command '/bin/sh -c bash build_scripts/build.sh && rm -r build_scripts' returned a non-zero code: 1
```

So it does seem like something is horribly wrong with the file system?
I don't have the hardware to try out if something is wrong with the docker image or Travis CI, but I was wondering if someone would have an idea of what's going on?

Could we somehow ignore these errors and still get a `manylinux2014_ppc64le` image? Or should we for now just ignore this architecture in `cibuildwheel`?

**Comment by mayeut** [comment]
Travis CI is working again on ppc64le
