### ISSUE TITLE
Travis timeouts breaking updates

### ISSUE THREAD

**Issue by njsmith** [pypa/manylinux#76]
It looks like #72 was merged a month ago, but still hasn't landed on the quay.io image, because the build timed out. I restarted it last night, and it timed out again. I just restarted it a second time -- who knows, maybe it'll work.

Offending build: https://travis-ci.org/pypa/manylinux/builds/138611073

The limit appears to be just under 50 minutes, and all of our recent master builds (including the successful ones) have been right up against this limit: https://travis-ci.org/pypa/manylinux/builds

I'm not sure what the right solution is but we need to do something about this :-(

**Comment by mayeut** [comment]
@njsmith 
I guess this has been fixed by 5d69b6ed68ce9d6d6e4df7ac1072567cf7048bee + 7ca443f9b7b10f4e7ee333d61cc526d3eb7259c4 and can now be closed ?
