### ISSUE TITLE
Updating autoconf is insufficient

### ISSUE THREAD

**Issue by ulope** [pypa/manylinux#77]
A newer version of autoconf was added through #72 unfortunately that is insufficient to build some libraries, leading to errors such as `error: Libtool library used but 'LIBTOOL' is undefined`.

Installing newer versions of automake and libtool fixes this.

I'm currently using the following as a workaround in my build script:

```
wget -q https://ftp.gnu.org/gnu/autoconf/autoconf-latest.tar.gz && tar zxf autoconf-latest.tar.gz && cd autoconf* && ./configure > /dev/null && make install > /dev/null && cd ..
wget -q https://ftp.gnu.org/gnu/automake/automake-1.15.tar.gz && tar zxf automake-*.tar.gz && cd automake* && ./configure > /dev/null && make install > /dev/null && cd ..
wget -q https://ftp.gnu.org/gnu/libtool/libtool-2.4.5.tar.gz && tar zxf libtool-*.tar.gz && cd libtool* && ./configure > /dev/null && make install > /dev/null && cd ..
```

**Comment by moisesguimaraes** [comment]
Having the same issue here, I'll try your fix, @ulope.

**Comment by rmcgibbo** [comment]
It might be useful to roll the latest libtool into the image. Here's the [section](https://github.com/pypa/manylinux/blob/master/docker/build_scripts/build.sh#L77-L83) of the build script where we build autoconf and automake. It should be straightforward to follow that pattern with libtool as well.

**Comment by moisesguimaraes** [comment]
PR created: https://github.com/pypa/manylinux/pull/136
