### ISSUE TITLE
Can't git clone in Docker image

### ISSUE THREAD

**Issue by polm** [pypa/manylinux#812]
Not sure if this is a bug or if I'm doing something wrong, but running into an error when using `git clone` with the docker image `pypa/manylinux1_x86_64`.

I originally had this in a separate Github Action [here][action], but recently moved it into an action in the repository I'm using it in. The code hasn't changed, but for some reason `git clone` fails with an error:

    /usr/local/libexec/git-core/git-remote-https: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory

An example run of the action is [here][action run], the code run in the Docker image is [here][entrypoint].

I have tried (re-)installing libcurl, curl-devel, and git, with no success. 

Am I doing something wrong? I would expect git clone to just work from the Docker image...

[action]: https://github.com/polm/mecab-manylinux1-wheel-builder/blob/master/entrypoint.sh
[entrypoint]: https://github.com/polm/fugashi/blob/master/.github/workflows/entrypoint.sh
[action run]: https://github.com/polm/fugashi/runs/1291013744?check_suite_focus=true

**Comment by polm** [comment]
Changing the `https://` url to a `git://` url fixed fthis for me, though I'm still unclear on why this worked in one case but not another.

**Comment by mayeut** [comment]
It seems that GitHub Actions is messing up the container configuration by passing `-e LD_LIBRARY_PATH` to the `docker run` command.
I don't know why they do this as it's not a documented behavior of GitHub Actions but it explains the issue.

e.g.
when not messing around with `LD_LIBRARY_PATH`, everything works:
```
Matt$ docker pull quay.io/pypa/manylinux1_x86_64
Using default tag: latest
latest: Pulling from pypa/manylinux1_x86_64
Digest: sha256:366923680436ebf01eba96b298053deeefb1ecc06d31cd91ad89584bcb88c5db
Status: Image is up to date for quay.io/pypa/manylinux1_x86_64:latest
quay.io/pypa/manylinux1_x86_64:latest
Matt$ docker run --rm -it quay.io/pypa/manylinux1_x86_64:latest /bin/bash
[root@ebcf017e0381 ~]# echo $LD_LIBRARY_PATH
/opt/rh/devtoolset-2/root/usr/lib64:/opt/rh/devtoolset-2/root/usr/lib:/usr/local/lib64:/usr/local/lib
[root@ebcf017e0381 ~]# git clone https://github.com/pypa/manylinux.git
Cloning into 'manylinux'...
remote: Enumerating objects: 2, done.
remote: Counting objects: 100% (2/2), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3256 (delta 1), reused 0 (delta 0), pack-reused 3254
Receiving objects: 100% (3256/3256), 2.87 MiB | 1.20 MiB/s, done.
Resolving deltas: 100% (2265/2265), done.
[root@ebcf017e0381 ~]# ls
manylinux
[root@ebcf017e0381 ~]# git clone git://github.com/pypa/manylinux.git manylinux2
Cloning into 'manylinux2'...
remote: Enumerating objects: 2, done.
remote: Counting objects: 100% (2/2), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3256 (delta 1), reused 0 (delta 0), pack-reused 3254
Receiving objects: 100% (3256/3256), 2.87 MiB | 1.49 MiB/s, done.
Resolving deltas: 100% (2265/2265), done.
[root@ebcf017e0381 ~]# ls
manylinux  manylinux2
[root@ebcf017e0381 ~]#
```
but when messing around with it, it does not work anymore:
Matt$ docker run --rm -it -e LD_LIBRARY_PATH quay.io/pypa/manylinux1_x86_64:latest /bin/bash
[root@7d963cce8a87 ~]# echo $LD_LIBRARY_PATH

[root@7d963cce8a87 ~]# git clone https://github.com/pypa/manylinux.git
Cloning into 'manylinux'...
/usr/local/libexec/git-core/git-remote-https: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory
[root@7d963cce8a87 ~]# git clone git://github.com/pypa/manylinux.git manylinux2
Cloning into 'manylinux2'...
remote: Enumerating objects: 2, done.
remote: Counting objects: 100% (2/2), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3256 (delta 1), reused 0 (delta 0), pack-reused 3254
Receiving objects: 100% (3256/3256), 2.87 MiB | 1.26 MiB/s, done.
Resolving deltas: 100% (2265/2265), done.
[root@7d963cce8a87 ~]# 
```

**Comment by polm** [comment]
Well that's bizarre, thanks for the explanation at least. I'd like to open issue with Github Actions but I'm not sure where that would go.

**Comment by mayeut** [comment]
Closing this as the issue lies in GitHub Actions.
@polm, if you have been able to open an issue with  Github Actions, can you please add the reference here please ? (I wouldn't know where to go either for this)

**Comment by magnetikonline** [comment]
@polm maybe I'm missing the point - but you're passing in `LD_LIBARAY_PATH` from the host into your Docker container?

```sh
docker run --rm -it -e LD_LIBRARY_PATH quay.io/pypa/manylinux1_x86_64:latest /bin/bash
```

**Comment by polm** [comment]
I am not passing the library path. The Dockerfile is here, and it's started by Github Actions - I don't call docker directly.

https://github.com/polm/fugashi/blob/master/.github/workflows/actions/build-manylinux/action.yml

What happened above is @mayeut is replicating my error by manually running docker. 

Also, since this issue has already been closed for being off-topic in this repo, it probably makes sense to have the discussion in `actions/setup-python` or somewhere else.

**Comment by magnetikonline** [comment]
> It seems that GitHub Actions is messing up the container configuration by passing `-e LD_LIBRARY_PATH` to the `docker run` command.

@polm right - that checks out. I'd probably raise this issue with GitHub, why the actions/workflow runner agent decides that all previously created env vars should be passed to Docker based Action images wholesale seems _very wrong_ to me.

Looking at the action authoring documentation https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-docker-container-action - can't see any obvious YAML properties to change this behaviour either.

**Comment by polm** [comment]
Where should I contact Github about this? It's really unclear to me what the right repo to file a report about this is.

**Comment by magnetikonline** [comment]
I would attempt here: https://github.com/actions/runner

**Comment by polm** [comment]
I did that and they told me it was a problem with actions/setup-python. 

https://github.com/actions/runner/issues/781

**Comment by magnetikonline** [comment]
I'm out of ideas then I'm afraid.

There is no reason Actions can't set these env vars `LD_LIBRARY_PATH` for their use - but the fact that inturn means all those custom ENV VAR mutations are passed into following Docker run commands for Actions seems to be very wrong - so personally I very much see the problem being with https://github.com/actions/runner - which is what I would be pushing for.

**Comment by polm** [comment]
OK, I have posted a followup in the runner ticket. I am still not sure why you continued the discussion here rather than on the issue in the setup-python issue.
