### ISSUE TITLE
Plans for python3.6 image?

### ISSUE THREAD

**Issue by ngoldbaum** [pypa/manylinux#82]
I'm curious whether there are any plans to have a Python3.6 manylinux image out soon after the final release next week.

**Comment by njsmith** [comment]
I think we should wait until the final release before adding this, just in
case of any last minute changes that affect abi. But obviously we will want
to get 3.6 support out asap once it's ready. There hasn't been any
discussion about it though :-). I guess if you want to help it along, now
would be a good time to make a PR for testing, that we could merge once the
release is final?

**Comment by matthew-brett** [comment]
Nathaniel - did you see the email by Nick Coghlan to the python packaging list : 

```
Resurrecting an old thread: this just came up on python-dev in the
context of ABI changes between alpha 3 and beta 3, and I've proposed
declaring the public ABI locked as part of the upcoming beta 4 release
(which is 3 weeks before the planned final release, while there's only
a single week planned between the first RC and the final release) to
give folks that want to pre-publish Python 3.6 wheel files more of an
opportunity to do so.
```

**Comment by njsmith** [comment]
For 3.5, they didn't *plan* to break ABI after rc1, but then they ended up doing an emergency ABI-breaking rc in the final week to fix a problem discovered at the last moment. (On Windows only, but still, it's not very reassuring...) I saw Nick's email, but I don't recall seeing anything from @ned-deily as 3.6 release manager agreeing to go along with it :-).

**Comment by ned-deily** [comment]
It's kind of a moot point now since 3.6.0rc1 is already out.  While it's a commendable goal, the (e.g. my) public position for 3.6 has been: "While the release is feature complete entering the beta phase, it is possible that features may be modified or, in rare cases, deleted up until the start of the release candidate phase (2016-12-05). Our goal is have no changes after rc1."  And while I'm going to do my very best to avoid *any* post-rc1 code changes prior to 3.6.0 final, there is always a non-zero probability that we might have to make some.  But, in any case, 3.6.0 final is scheduled for just a week away.

**Comment by matthew-brett** [comment]
@ned-deily - thanks for the feedback.

I think you are saying that we cannot depend on ABI compatibility with the final release? 

The thing that we're worried about, is that, if we have to wait until the final release, then everyone using the new Python release will suddenly have all their wheel installations fail and revert to source builds, some of which are very likely to fail.  This will be a pretty bad user experience, and the more successful the wheels are, the worse it gets for the release breakage.

Is there any way of having a guaranteed 2 week window between the final build and the final release, during which we could build at least the major wheels, such as numpy and scipy?

**Comment by takluyver** [comment]
I tried adding 3.6 in #89, but there are one or two problems to resolve. I'm still only sporadically available for a few more days, so if someone has the time to get it working, please don't wait for me.
