### ISSUE TITLE
Older versions of libmagic/file-devel present in manylinux2014 can't read newer /usr/share/misc/magic

### ISSUE THREAD

**Issue by dralley** [pypa/manylinux#823]
I have a package that includes the ```file-devel``` library (also known as ```libmagic``` on Debian-based systems).  When I build a ```manylinux2014``` compatible package and use it on Centos 7, it works.  When I use the very same package on Fedora 32, it does not work - I get failing tests and many, many terminals worth of warnings that look like the following:

```
/usr/share/misc/magic, 30371: Warning: type `name				help-ver-date' invalid
/usr/share/misc/magic, 30414: Warning: type `se 		help-ver-date' invalid
/usr/share/misc/magic, 30418: Warning: type `se 		help-ver-date' invalid
/usr/share/misc/magic, 30421: Warning: type `se 		help-ver-date' invalid
/usr/share/misc/magic, 30424: Warning: type `se 		help-ver-date' invalid
/usr/share/misc/magic, 30427: Warning: type `se 		help-ver-date' invalid
/usr/share/misc/magic, 30430: Warning: type `se 		help-ver-date' invalid
/usr/share/misc/magic, 30434: Warning: type `se 		help-ver-date' invalid
/usr/share/misc/magic, 30484: Warning: type `se 		cnt-name' invalid
/usr/share/misc/magic, 30490: Warning: type `se 		cnt-name' invalid
/usr/share/misc/magic, 30493: Warning: type `name				cnt-name' invalid
/usr/share/misc/magic, 30542: Warning: type `leqwdate	x	\b, ctime=%s' invalid
/usr/share/misc/magic, 30543: Warning: type `leqwdate	x	\b, mtime=%s' invalid
/usr/share/misc/magic, 30544: Warning: type `leqwdate	x	\b, atime=%s' invalid
/usr/share/misc/magic, 30633: Warning: type `se		ini-file' invalid
/usr/share/misc/magic, 30636: Warning: type `se		ini-file' invalid
/usr/share/misc/magic, 30639: Warning: type `se		ini-file' invalid
/usr/share/misc/magic, 30641: Warning: type `name		ini-file' invalid
/usr/share/misc/magic, 31024: Warning: type `se		wim-archive' invalid
/usr/share/misc/magic, 31027: Warning: type `se		wim-archive' invalid
/usr/share/misc/magic, 31028: Warning: type `name		wim-archive' invalid
/usr/share/misc/magic, 31710: Warning: type `clear	x' invalid
/usr/share/misc/magic, 31831: Warning: type `name		zipcd' invalid
/usr/share/misc/magic, 31834: Warning: type `se		zipversion' invalid
/usr/share/misc/magic, 31836: Warning: type `se		zipversion' invalid
/usr/share/misc/magic, 31840: Warning: type `se		zipcompression' invalid
/usr/share/misc/magic, 31843: Warning: type `name		zipcompression' invalid
/usr/share/misc/magic, 31856: Warning: Printf format `#' is not valid for type `leshort' in description `[%#x]'
/usr/share/misc/magic, 31859: Warning: type `name		zipversion' invalid
/usr/share/misc/magic, 31876: Warning: Printf format `#' is not valid for type `leshort' in description `v?[%#x]'
/usr/share/misc/magic, 31885: Warning: type `se		zipcd' invalid

```

My assumption is the older ```file-devel``` can't properly read the newer ```/usr/share/misc/magic``` database file (on the host system) that describes which file types have which "magic number" identifiers.

This is a hard problem and I'm not really sure what the answer is.  Upgrade the library in-place?  Release a ```manylinux2018```?  Blacklist the library if there is no good answer?

It blocks us from making our binary packages available on PyPI, we're stuck with source packages only.

**Comment by mayeut** [comment]
If https://github.com/file/file provides backward compatibility in reading `/usr/share/misc/magic`, then your best bet is to build the latest version from sources and link with this one. Otherwise, you're stuck with source packages only.

**Comment by mayeut** [comment]
Answered, closing.

**Comment by dralley** [comment]
@mayeut I assume there is no chance that libfile would become one of the "blessed" packages (like glibc) considering it is heavily tied to the platform itself?

Even if we took the latest version and built from source, the packages built today might break on the distros of the future, because ```/usr/share/misc/magic``` is a moving target.

**Comment by dralley** [comment]
Unless newer version are forwards-compatible, in which case, it would be better if you just provide such a version in the manylinux environment.
