### ISSUE TITLE
Maintainer for manylinux image?

### ISSUE THREAD

**Issue by matthew-brett** [pypa/manylinux#83]
Are there one or more official maintainers for this image?     I ask because I am getting the impression maintenance is starting to drift, and it would be good to establish whether there is anyone who feels able to take responsibility for maintenance.

**Comment by njsmith** [comment]
Currently the people with commit bits are you, me, @ogrisel and @rmcgibbo. I'm not sure what you're asking for exactly. You know that there's no-one who's "officially in charge", unless you'd like to be :-). I agree that the project could benefit from a bit more attention, but I'm not sure how to make that happen. And in the mean time, this state where it's sort of ticking along inefficiently on dribs and drabs of volunteer time is a sub-optimal but pretty common state for a F/OSS project to be in...

**Comment by matthew-brett** [comment]
I might be wrong, but my current impression is that everyone is waiting for someone else to take over maintenance, leaving a depressing void of not-me in the center.

I don't want to take over maintenance.  I know we all have a duty to take on these kinds of responsibilities in general, but I already do the lion's share of wheel building and maintenance across the scientific Python stack, so I would claim to have paid my maintenance dues in that respect.

So - @njsmith @rmcgibbo @ogrisel - are any of you prepared to step up for this task?   It seems to me it wouldn't be an enormous amount of work, would be of benefit to the wider community, and that having a named maintainer would help the current situation a great deal.

**Comment by rmcgibbo** [comment]
@matthew-brett: I agree with your assessment of the situation, and I agree it's suboptimal. More ongoing maintenance would help.

I pushed a lot on this project (auditwheel, working on the PEP with @njsmith, etc) last winter while procrastinating on finishing up my Ph.D. Since then, my personal circumstances have changed a lot (I got a job, moved to a new city, etc), and the amount of time I have to work on F/OSS has gone down substantially.

With that said, I'm not sure that naming anyone as "officially in charge" would be better than the current system.

**Comment by matthew-brett** [comment]
Robert - thanks for the update - completely reasonable that you haven't got time right now to do the maintenance.

I'm afraid we're already running into trouble with maintenance, and I doubt the current 'everyone wait for everyone else' strategy is going to work any better in the future.

Olivier, Nathaniel - can you do this job?

**Comment by natefoo** [comment]
My time is pretty limited but I'm willing to throw in with the rest of you in a "not in charge but can do stuff as time allows" capacity.

**Comment by rmcgibbo** [comment]
@natefoo: Awesome
@matthew-brett: what's at the top of your list for issues that need to be triaged? py36?

**Comment by njsmith** [comment]
@brosner / @carljm / @dstufft / @qwcode: can someone add @natefoo to the pypa/manylinux team? ("natefoo is not a member of this organization; only organization owners can send invitations")

**Comment by dstufft** [comment]
I have invited @natefoo!

**Comment by auvipy** [comment]
can we close this now? as we got some new maintainers
