### ISSUE TITLE
Use vault repositories for EOL CentOS 6

### ISSUE THREAD

**Issue by guillaumekln** [pypa/manylinux#836]
CentOS 6 is EOL since November 30th, 2020. The main repositories appear to be offline:

```text
Error: Cannot find a valid baseurl for repo: base
YumRepo Error: All mirror URLs are not using ftp, http[s] or file.
 Eg. Invalid release/repo/arch combination/
removing mirrorlist with no valid mirrors: /var/cache/yum/x86_64/6/base/mirrorlist.txt
```

Can the `manylinux2010` image be updated to point to the [vault repositories](https://vault.centos.org/centos/6.10/)?

For reference, here is the commit that did the same for CentOS 5: https://github.com/pypa/manylinux/commit/73e58823b5fbba8647a23ce70285ab76949b4ceb

Thanks.

**Comment by jamadden** [comment]
This is also biting me ([full logs of a failed github action](https://github.com/gevent/gevent/runs/1489046087?check_suite_focus=true#step:5:56) that's running [this script](https://github.com/gevent/gevent/blob/20.9.0/scripts/releases/make-manylinux#L52)).
