### ISSUE TITLE
[Manylinux2010] Unable to install package

### ISSUE THREAD

**Issue by MonkeyBreaker** [pypa/manylinux#843]
Hello everyone,

Our pipeline using `manylinux2010` was affected by issue #836, the fix you merged seemed to resolve the first problem raised.
But, in our pipeline, `yum` was then unable to find a package we needed, `ccache`, we where getting the following:

```
+ yum install -y ccache
Loaded plugins: ovl
Setting up Install Process

base                                                     | 3.7 kB     00:00     
...
base/primary_db           89% [=============  ] 1.0 MB/s | 4.2 MB     00:00 ETA 

base/primary_db                                          | 4.7 MB     00:03     

centos-sclo-rh                                           | 3.0 kB     00:00     
...
centos-sclo-rh/primary_db 79% [===========-   ] 764 kB/s | 1.2 MB     00:00 ETA 

centos-sclo-rh/primary_db                                | 1.5 MB     00:01     

centos-sclo-sclo                                         | 2.9 kB     00:00     

centos-sclo-sclo/primary_db                              | 166 kB     00:00     

extras                                                   | 3.4 kB     00:00     

extras/primary_db                                        |  29 kB     00:00     

updates                                                  | 3.4 kB     00:00     
...
updates/primary_db        97% [==============-] 1.3 MB/s |  11 MB     00:00 ETA 

updates/primary_db                                       |  12 MB     00:07     
No package ccache available.
Error: Nothing to do
```

Looking around what could be the problem, I did not understand everything, but one fix that currently allows us to make things work again is to install first this:

`yum install -y https://archives.fedoraproject.org/pub/archive/epel/6/x86_64/epel-release-6-8.noarch.rpm`

Seems to install `epel` first. 

But, even if it does currently work again, I would like to know if this is the best approach to be able to install again a package like `ccache`, or if there's a better/official approach to this that I did not find yet ?

Thank you for any insights you can provide me.

Best,
Julián

PS: The current version of `manylinux2010` we use is: `quay.io/pypa/manylinux2010_x86_64:2020-12-03-912b0de`

**Comment by MonkeyBreaker** [comment]
Hi,

Thank you for the fix. I reverted the "hack" and now installing with `yum` seems to work again.
But, now `wget` started to fail with `ERROR: cannot verify d29vzk4ow07wi7.cloudfront.net’s certificate, issued by ...`, easy fix is to add option `--no-check-certificate`.

Anyway, I think that we will move to a more recent `manylinux`.

Thank you again and have a nice day,
Julián

**Comment by mayeut** [comment]
The issue you're now seeing is related to `certifi` update.
The related root CA has been removed c.f. https://bugzilla.mozilla.org/show_bug.cgi?id=1670769#c0
All images should behave the same.

If you do trust the CA, you can at your own risk overwrite the environment variable `SSL_CERT_FILE` to another CA bundle (e.g. the one provided by `certifi 2020.11.8`)
