### ISSUE TITLE
Publish quay.io/pypa/manylinux2010_centos-6-no-vsyscall

### ISSUE THREAD

**Issue by mayeut** [pypa/manylinux#878]
Now that CentOS 6 is EOL, I don't expect the base image used for `manylinux2010_x86_64` `quay.io/pypa/manylinux2010_centos-6-no-vsyscall` to ever change and it might be time to publish it.

It will decrease build time & simplify build scripts.

Pre-requisite: #874 

@pypa/manylinux, any thought ? Shall it be renamed ?

**Comment by rdb** [comment]
It is currently impossible for anyone to actually build manylinux2010 from the repository:
```
Sending build context to Docker daemon  19.28MB
Step 1/25 : FROM quay.io/pypa/manylinux2010_centos-6-no-vsyscall
unauthorized: access to the requested resource is not authorized
```
Any chance this could be fixed?

**Comment by mayeut** [comment]
@rdb, This will be fixed shortly. If you are rebuilding `manylinux2010` on your end for whatever reason, you might be interested in #877 that will end up changing some things for you.

xref #481 (issues caused by the base image not being published)
