### ISSUE TITLE
Adding support for 3.10 pre-release to manylinux images

### ISSUE THREAD

**Issue by crwilcox** [pypa/manylinux#949]
Currently Python 3.10 is in Alpha 4 (3.10a4). Any chance of including 3.10-dev, or the latest candidates in images? This would enable projects I work on to get ahead of the release for 3.10 and avoid delays in delivering wheels for customers using the latest python versions.

Thanks!

**Comment by mayeut** [comment]
Please not that the ABI is not frozen yet and that wheels built with CPython 3.10.0b1 shall not be published to PyPI yet.
Excerpt from https://www.python.org/downloads/release/python-3100b1/:
> We **strongly encourage** maintainers of third-party Python projects to **test with 3.10** during the beta phase and report issues found to [the Python bug tracker](https://bugs.python.org/) as soon as possible. While the release is planned to be feature complete entering the beta phase, it is possible that features may be modified or, in rare cases, deleted up until the start of the release candidate phase (Monday, 2021-08-02). Our goal is have no ABI changes after beta 4 and as few code changes as possible after 3.10.0rc1, the first release candidate. To achieve that, it will be **extremely important** to get as much exposure for 3.10 as possible during the beta phase.

ABI freeze is expected at 3.10.0b4 for now.

You can subscribe to this issue to get notified of beta updates in manylinux images and when to expect ABI freeze if that changes along the way.

**Comment by mayeut** [comment]
3.10.0b4 is now in the latest images.
ABI should be stable: https://www.python.org/downloads/release/python-3100b4/

**Comment by mayeut** [comment]
3.10.0rc1 is now in the latest images.
ABI is now stable: https://www.python.org/downloads/release/python-3100rc1/
