### ISSUE TITLE
Manylinux wheel not working on self-compiled python

### ISSUE THREAD

**Issue by kawing-chiu** [pypa/manylinux#97]
I've found a situation where manylinux wheels don't work. I think it might be bug. To reproduce:

(On cpython source directory cloned from github)
```
$ git checkout v3.5.3
$ ./configure --with-pydebug
$ make -j 7
$ ./python -m venv test_env
$ source test_env/bin/activate
```
Then install some package that has a manylinux wheel, for example sip and pillow:
```
(test_env) $ pip install sip
Collecting sip
  Could not find a version that satisfies the requirement sip (from versions: )
No matching distribution found for sip
```
```
(test_env) $ pip install pillow
Collecting pillow
  Downloading Pillow-4.0.0.tar.gz (11.1MB)
  (the source package is being downloaded, not the manylinux wheel)
```
The same packages can be installed via manylinux wheel if using the system's python on the same system, only fails on a self-compiled python. (My system is Arch Linux x86_64)

**Comment by njsmith** [comment]
If you use `--with-pydebug` it changes the internal memory layout of Python objects. This means that extensions built for a regular Python build can't be used on a `--with-pydebug` build, and vice-versa.

In principle sip and pillow could upload both regular and pydebug wheels, but in practice no-one does this. So pip is quite correctly noticing that there are no wheels available that are compatible with your Python build, and falling back on trying to use a source package instead.

**Comment by kawing-chiu** [comment]
Thanks for the explanation!
