### ISSUE TITLE
update libz.so

### ISSUE THREAD

**Issue by mattip** [pypa/manylinux#986]
xref numpy/numpy#18299 which mentions that the version of libz.so in the manylinux1 and manylinux2010 image has libz.so==1.2.3 which is very old and has some unclear pointer arithmetic problems. Even the libz in the manylnux2014 image, 1.2.7, is not up to date.

**Comment by mayeut** [comment]
xref pypa/auditwheel#152

Not checked yet but I hope `libz` from manylinux2010 & manylinux2014 are not affected by the CVE and were fixed by RedHat/CentOS.

**Comment by mayeut** [comment]
@mattip,

auditwheel 5 adds `libz.so.1` to the list of whitelisted libraries so this shouldn't be an issue anymore.
