### ISSUE TITLE
cffi fails to build in latest images

### ISSUE THREAD

**Issue by glandium** [pypa/manylinux#996]
It used to build fine a few days ago, and is broken as of the latest images. 

It seems the regression happened somewhere between 2021-01-24-91ce2b8 and 2021-02-06-93da623 for the manylinux2014 images and somewhere between 2021-02-06-3d322a5 and 2021-02-07-7816579 for the manylinux2010 images.

Example of failure log: https://github.com/indygreg/python-zstandard/pull/137/checks?check_run_id=1879152214

Cc: @indygreg

**Comment by glandium** [comment]
The link apparently died. Here's an excerpt of the log:
```
   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/opt/_internal/cpython-3.9.1/include/python3.9 -c c/_cffi_backend.c -o build/temp.linux-i686-3.9/c/_cffi_backend.o
    c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
              ^~~~~~~
    compilation terminated.
    error: command '/opt/rh/devtoolset-8/root/usr/bin/gcc' failed with exit code 1
    ----------------------------------------
    Running setup.py install for cffi: finished with status 'error'
```

It seems libffi headers are not there anymore, while they're apparently useful to build cffi modules with python 3.9.

**Comment by glandium** [comment]
Earlier in the log:
```
Collecting cffi==1.13.2
```
and cffi 1.13.2 doesn't have a wheel for python 3.9. So the problem is really that cffi itself doesn't build in the new images.

**Comment by mayeut** [comment]
fixed in `python-zstandard`: indygreg/python-zstandard#140

**Comment by yuangu** [comment]
I have the same problem
